### ISSUE TITLE
2.4-2.5: Separate Credentials

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-spring#129]
**[Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#separate-credentials)**
The new script-based SQL database initialization does not support using separate credentials for schema (DDL) and data (DML) changes. This reduces complexity and aligns its capabilities with Flyway and Liquibase. If you require separate credentials for schema and data initialization, define your own `org.springframework.jdbc.datasource.init.DataSourceInitializer` beans.

**Condition**
- `spring.datasource.schema` and `spring.datasource.data` exist
- `spring.datasource.schema` and file `classpath:/**/data.sql` exist
- `spring.datasource.data` and file `classpath:/**/schema.sql` exist
- Files `classpath:/**/schema.sql` and `classpath:/**/data.sql` exist
- `spring.datasource.schema-username` and `spring.datasource.schema-password` exist

>Problem: It is possible (but unlikely) that all conditions are `false` but the given properties are provided as env or startup parameters. See #461 

**Recipe**
`boot-2.4-2.5-datasource-initializer`

**Actions**

- If property `spring.datasource.data-username` exists
  -  rename property to `spring.sql.init.username`
- If property `spring.datasource.schema-username` exists 
  - keep the property (will be shown as deprecated). Changing it could affect application 
  startup if this property is provided on startup
- If property `spring.datasource.schema` exists
  - rename property to `spring.sql.init.schema-locations`
- If property 'spring.datasource.data` exists
  - rename property to `spring.sql.init.data-locations`    
- Create a `DataSourceInitializer` bean config which conditional on property  `spring.datasource.schema-username` <br>

````
@ConditionalOnProperty(
    value="spring.datasource.schema-username", 
    matchIfMissing = false)
````

- The bean defines a datasource for DDL scripts which uses `spring.datasource.schema-username` and `spring.datasource.schema-password` as credentials and files from `spring.sql.init.schema-locations` if the property is set or the path for `schema.sql` if the property is not set.

**Comment by timtebeek** [comment]
The renamed properties have mostly been picked up automatically from the exposed configuration metadata:
https://github.com/openrewrite/rewrite-spring/blob/b13ef1ddf0767573346f986457b9c196721ee524/src/main/resources/META-INF/rewrite/spring-boot-25-properties.yml#L40-L72

**Comment by timtebeek** [comment]
I'm doubtful that we still want to add that `@ConditionalOnProperty(...) DataSourceInitializer` now, and lean towards closing this issue. What are your thoughts on that @fabapp2 ?

**Comment by timtebeek** [comment]
One year on; closing this issue.
