### ISSUE TITLE
spring.profiles vs spring.config.activate.on-profile

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite-spring#132]
Good afternoon, 

I have checked that when migrating to Spring Boot 2.4 (**org.openrewrite.java.spring.boot2.SpringBootProperties_2_4**), you migrate the **spring.profiles** property to **spring.config.activate.on-profile**, and I really consider that it is not correct since both properties are still valid and are used differently as you can read in this article https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4

I have made a test and I can't get the application-local.yml to load using the spring.config.activate.on-profile.active property.

https://github.com/openrewrite/rewrite-spring/blob/1121fe5b9bf069553c51e6c35a8400a4d69c74d4/src/main/resources/META-INF/rewrite/spring-boot-configuration-migration.yml#L1443-L1448

**Comment by pway99** [comment]
thanks @josemariavillar we'll have a look

**Comment by josemariavillar** [comment]
Good morning @pway99,

With regard to this issue, do you know what is the forecast for it to be solved?

**Comment by tkvangorder** [comment]
@josemariavillar Sorry this took so long to resolve!

This was fixed rewrite-core via this PR: https://github.com/openrewrite/rewrite/pull/2066

This fix is included with version 4.25.1 (or newer) of rewrite-spring
