### ISSUE TITLE
2.4-2.5: Task Scheduling Harmonization with Spring Integration

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-spring#138]
[Release Notres](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#task-scheduling-harmonization-with-spring-integration)
Spring Integration now reuses an available `TaskScheduler` rather than configuring its own. In a typical application setup relying on the auto-configuration, this means that Spring Integration uses the auto-configured task scheduler that has a pool size of 1. To restore Spring Integration’s default of 10 threads, use the `spring.task.scheduling.pool.size` property.

### Condition
- spring integration is on the classpath `org.springframework.integration:spring-integration-core`

#### Description

> The scan found `org.springframework.integration:spring-integration-core` on the classpath.
> Spring Integration now reuses an available `TaskScheduler` rather than configuring its own. In a typical application setup relying on the auto-configuration, this means that Spring Integration uses the auto-configured task scheduler that has a pool size of 1. To restore Spring Integration’s default of 10 threads, use the `spring.task.scheduling.pool.size` property.

**Comment by fabapp2** [comment]
We could set the property to the old default and inform the user that the new default was overwritten and what to do to reset it to Spring Boot 2.5 new default? (automated)
Otherwise, we inform about the change and stay on the new Spring Boot 2.5 default? (manual)

**Comment by pway99** [comment]
that sounds reasonable, let the user make the final decision in the code-review process.
