### ISSUE TITLE
Upgrade Gradle for spring projects using Spring Boot 2.5 to at least version 6.8

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-spring#146]
[Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#minimum-requirements-changes)
Projects built with Gradle now require Gradle 6.8 or later.

### Condition
- Gradle is used
- Gradle version < 6.8

#### Description
> Projects built with Gradle now require Gradle 6.8 or later.

**Comment by shanman190** [comment]
Fixed via #382.
