### ISSUE TITLE
2.4-2.5: Notable Deprecations in Spring Boot 2.5

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-spring#148]
[Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#notable-deprecations-in-spring-boot-25)
The following notable deprecations have been made in Spring Boot 2.5

-   `ActuatorMediaType` and `ApiVersion` in `org.springframework.boot.actuate.endpoint.http` in favor of equivalents in `org.springframework.boot.actuate.endpoint` https://github.com/openrewrite/rewrite-spring/commit/78ff1ae8bba9ceddd6e8ff1c1427744cb5e47503
    
-  ~Support for beans that implement jOOQ’s `*Provider` callback interfaces or `Settings` has been deprecated. A `DefaultConfigurationCustomizer` should be used instead.~ (#144)
    
-   `EntityManagerFactoryDependsOnPostProcessor` in `org.springframework.boot.autoconfigure.data.jpa` has been relocated to `org.springframework.boot.autoconfigure.orm.jpa` 038224b2cb7167032e9b98ca9aab055ab488fbc8

**Comment by pway99** [comment]
potential declarative recipe

**Comment by pway99** [comment]
completed the three notable deprecations
