### ISSUE TITLE
2.4-2.5: Deprecated properties

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-spring#149]
[Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#new-and-noteworthy)
Check [the configuration changelog](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-NotesSpring-Boot-2.5.0-Configuration-Changelog) for a complete overview of the changes in configuration.

### Condition
- Any property in [the list of deprecated properties](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5.0-Configuration-Changelog#deprecated-in-250) was found

#### Description
> The property `...` was found but was deprecated in 2.5 and should be replaced by `...`

**Comment by pway99** [comment]
Confirmed that all 2.5 and 2.6 properties are accounted for in the `spring-boot-upgrade-version.yml`
