### ISSUE TITLE
SpringBoot2JUnit4to5Migration: Test Rules Annotations

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite-spring#173]
Good afternoon, 

When executing the SpringBoot2JUnit4to5Migration recipe on a test containing a `@Rule` annotation, this annotation is not migrated. As I have been able to read in the guide [Migrating from JUnit 4 to JUnit 5](https://www.baeldung.com/junit-5-migration#6-new-test-rules-annotations) the `@Rule` and `@ClassRule` annotations were used to add a special functionality to the tests and in JUnit5 the same logic can be reproduced using the `@ExtendWith` annotation.

According to the JUnit guide, the @Rule and @ClassRule annotations no longer exist; they have been replaced by @ExtendWith and @RegisterExtension.

https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-tips

Thank you very much for the excellent support you provide

Thanks & regards

**Comment by pway99** [comment]
Hello @josemariavillar,

Thanks for the suggestion there are quite a few variations of junit `@Rule` implementations.  Currently, the following recipes handle `org.junit.Rule` migrations. do you have any specific rules in mind?  
- [TestRuleToTestInfo](https://github.com/openrewrite/rewrite-testing-frameworks/blob/8a6dc535a5defe20940965ffdb5a7b2549ac5c83/src/main/java/org/openrewrite/java/testing/junit5/TestRuleToTestInfo.java#L77)
- [UpdateMockWebServer](https://github.com/openrewrite/rewrite-testing-frameworks/blob/8a6dc535a5defe20940965ffdb5a7b2549ac5c83/src/main/java/org/openrewrite/java/testing/junit5/UpdateMockWebServer.java#L48)
- [TemporaryFolderToTempDir](https://github.com/openrewrite/rewrite-testing-frameworks/blob/8a6dc535a5defe20940965ffdb5a7b2549ac5c83/src/main/java/org/openrewrite/java/testing/junit5/TemporaryFolderToTempDir.java#L36)

`@ClassRule` and `@MethodRule` are generic extensibility mechanisms. So each way they are implemented in practice has to be handled individually. 

Perhaps there is an extension or some other standard conversion for the `@ClassRule` your needing to migrate. Do you have an example we can look at?

**Comment by josemariavillar** [comment]
Good morning, 

thanks for the information, it is quite useful, but wouldn't it be correct to update the @Rule and @ClassRule annotations by @ExtendWith regardless of their implementation? As the JUnit documentation itself specifies: "@Rule and @ClassRule no longer exist; superseded by @ExtendWith and @RegisterExtension".

Thanks & regards

**Comment by pway99** [comment]
Good morning,

> wouldn't it be correct to update the `@Rule` and `@ClassRule` annotations by `@ExtendWith` regardless of their implementation?

I do not think that is correct, per the documentation `@ClassRule` annotates static fields or public methods that reference `TestRule` subtypes.  Because `TestRule` is not a supported _Extension API_ it is not possible to replace `@ClassRule` annotations with `@ExtendsWith`.
[ClassRule](https://junit.org/junit4/javadoc/4.12/org/junit/ClassRule.html) - [TestRule](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TestRule.html)
[ExtendWith](https://junit.org/junit5/docs/5.0.3/api/org/junit/jupiter/api/extension/ExtendWith.html) - [Extension](https://junit.org/junit5/docs/5.0.3/api/org/junit/jupiter/api/extension/Extension.html)

Kind Regards
