### ISSUE TITLE
Remove cglib dependency

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-spring#186]
I was working on an older code base and it had cglib among other versions that should be removed when performing a migration to 5.x.  Here were the entries that should be removed:

```xml
<dependency>
  <groupId>org.aspectj</groupId>
  <artifactId>aspectjrt</artifactId>
  <version>1.6.0</version>
</dependency>

<dependency>
  <groupId>org.aspectj</groupId>
  <artifactId>aspectjweaver</artifactId>
  <version>1.6.0</version>
</dependency>

<dependency>
  <groupId>aopalliance</groupId>
  <artifactId>aopalliance</artifactId>
  <version>1.0</version>
</dependency>

<dependency>
  <groupId>cglib</groupId>
  <artifactId>cglib</artifactId>
  <version>2.2.2</version>
</dependency>
```

**Comment by pway99** [comment]
Hi @rdifrango,
Starting looking at this, I am a bit concerned about just removing dependencies and leaving the project in a broken state.  Do you have a sample project we can look at or can you provide some info to support just removing the dependencies?
Thanks and kind regards,
Pat

**Comment by rdifrango** [comment]
The need for cglib explicitly was removed back in Spring 3.2 as they now repackage it within Spring APP:

https://docs.spring.io/spring-framework/docs/3.2.0.RELEASE/spring-framework-reference/html/migration-3.2.html

**Comment by rdifrango** [comment]
Unfortunately I can't share our internal project but if I get a chance I'll try and work up a sample of doing so.

**Comment by rdifrango** [comment]
I wanted to circle back

1. CGLIB being repackaged is show [here](https://github.com/spring-projects/spring-framework/blob/main/spring-core/spring-core.gradle)
2. AOP Alliance is now also included in their source [here](https://github.com/spring-projects/spring-framework/tree/main/spring-aop/src/main/java/org/aopalliance).
3. aspectj as a dependency set [here](https://github.com/spring-projects/spring-framework/blob/main/build.gradle#L54-L58)

**Comment by pway99** [comment]
Thanks @rdifrango

**Comment by rdifrango** [comment]
Thank you @pway99 !
