### ISSUE TITLE
2.7+ Migration: @Local*Port annotations moved to spring-boot-test

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#190]
https://github.com/spring-projects/spring-boot/commit/48f8021d88ef0591d7b931b2a9bc6d4d48247d58 via https://github.com/spring-projects/spring-boot/releases/tag/v2.7.0-RC1

So replace these annotations, and possibly add the `spring-boot-test` dependency.
```diff
-import org.springframework.boot.web.server.LocalServerPort;
+import org.springframework.boot.test.web.server.LocalServerPort
-import org.springframework.boot.actuate.autoconfigure.web.server.LocalManagementPort;
+import org.springframework.boot.test.web.server.LocalManagementPort;
-import org.springframework.boot.rsocket.context.LocalRSocketServerPort;
+import org.springframework.boot.test.rsocket.server.LocalRSocketServerPort;
```

**Comment by tkvangorder** [comment]
This looks reasonable to me, thanks for the suggestion!

**Comment by timtebeek** [comment]
You're welcome; did a first stab at implementation already in https://github.com/openrewrite/rewrite-spring/pull/191.

You might want to retarget to something like a 2.7.x branch, as there's [more changes needed](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes).

- [ ] There's easy changes such as the one to one okhttp & mustache property changes.
- [ ] You might want to include the [OkHttp4 MockWebServer recipe](https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/UpdateMockWebServer.java#L42).

There's some [metric tag keys renamed](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#metric-tag-keys-renamed); but I don't see those requiring a recipe, as they would just change in your metrics backend.

There's also [a few deprecations](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#deprecations-in-spring-boot-27) that would be removed in 2.8 or 3.0. These would not be required to upgrade to 2.7 yet, but could be nice to add already.
