### ISSUE TITLE
Spring Security 5.7: Replace deprecated WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#194]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes
https://github.com/spring-projects/spring-security/releases/tag/5.7.0
https://github.com/spring-projects/spring-security-samples/commit/c5a2162b07c300378ec7bafe9f2ff958e5906583
https://github.com/spring-projects/spring-security-samples/commit/fe037cf4d7b6b112444287f3741f7c208ce5ff98

Steps to migrate:
1. Any class that extends `extends WebSecurityConfigurerAdapter` should no longer do so; remove the import.
2. `@Override` of `protected void configure(HttpSecurity http)` should be replaced by `@Bean public SecurityFilterChain securityFilterChain(HttpSecurity http)` with the same body, with a new final `return http.build();`
3. One might also have to add `@EnableWebSecurity` if not present elsewhere.

**Comment by pway99** [comment]
Thanks for the detailed description @timtebeek

**Comment by pway99** [comment]
@BoykoAlex thanks for your [PR](https://github.com/openrewrite/rewrite-spring/pull/202) for this request

**Comment by pway99** [comment]
closed by: https://github.com/openrewrite/rewrite-spring/pull/202
