### ISSUE TITLE
2.7 Changes to Auto-Configuration

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#197]
https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/howto.html#howto.testing.slice-tests

> **Auto-configuration Registration**
If you have created your own auto-configurations, you should move the registration from spring.factories to a new file named META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports. Each line contains the fully qualified name of the auto-configuration. See [the included auto-configurations](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports) for an example.
> 
> For backwards compatibility, entries in spring.factories will still be honored.

So:
1. Any `src/main/resources/META-INF/spring.factories` file should move to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
2. the comma separate value for key `org.springframework.boot.autoconfigure.EnableAutoConfiguration` should be split across separate lines.

> **New @AutoConfiguration Annotation**
A new @AutoConfiguration annotation has been introduced. It should be used to annotate top-level auto-configuration classes that are listed in the new META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports file, replacing @Configuration. Configuration classes that are nested within or imported by an @AutoConfiguration class should continue to use @Configuration as before.
> 
> For your convenience, @AutoConfiguration also supports auto-configuration ordering via the after, afterNames, before and beforeNames attributes. This can be used as a replacement for @AutoConfigureAfter and @AutoConfigureBefore.

So:
1. Replace usage of `@Configuration` with `@AutoConfiguration` where classes are mentioned in the above replaced `src/main/resources/META-INF/spring.factories`

> **Test Slice Configuration**
> If you have created your own test-slices, you should move the registration from spring.factories to the new place under META-INF/spring/<name of your test slice annotation>.imports. The format is the same as the new file described in the "Auto-configuration Registration" section, see above.
> 
> See [the included test slices for an example](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-test-autoconfigure/src/main/resources/META-INF/spring/).

Above steps are complicated even more for users defining their own test slices, requiring a different filename with the same one class per line structure as above.

**Comment by timtebeek** [comment]
I'd guess somewhat lower priority as compared to other issues, as own auto configuration classes are not as often used. Typically only in company/team wide starter libraries. But still, changes like these could go unnoticed in a migration, until they break at a later date, since backwards compatibility is still there.

**Comment by pway99** [comment]
Thanks @timtebeek,  
Now that unsupported file types are represented as Quarks its possible to detect and rename the file, unfortunately, it's not possible to modify Quark source contents.  Perhaps this recipe could add a SearchMarker to the project pom with a message providing transformation instructions.

**Comment by jkuipers** [comment]
Note that this isn't quite correct:
> Any src/main/resources/META-INF/spring.factories file should move to META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

That spring.factories file can contain other entries besides autoconfiguration, so only when moving that entry would leave an empty file should you remove it: otherwise it should be left in place with just that entry removed.

**Comment by timtebeek** [comment]
[As discussed](https://twitter.com/jkuipers/status/1573325263731134466), this is already [covered in Spring Boot Migrator](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade/common/actions/CreateAutoconfigurationAction.java#L36). Might already resolve this issue here, unless we want to pull that up into Rewrite-Spring.
