### ISSUE TITLE
WebSecurityConfigurerAdapter migration recipe often not applied

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#214]
There's a hint from @BoykoAlex in this https://github.com/openrewrite/rewrite-spring/pull/202#issuecomment-1155782542
> I have pushed the revised version of the Recipe to play it safe when non applicable methods are overridden and/or used within the same class declaration.

Tried it on a few projects, but it seems the play-it-safe is quite restrictive. Having any unrelated method in the same class is already enough for the migration to back off. Consider the following sample, where I've only added a single line method to t[he first `assertChanged` test in `WebSecurityConfigurerAdapterTest.kt`](https://github.com/openrewrite/rewrite-spring/blob/main/src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterTest.kt#L39).

```
package com.example.websecuritydemo;

import static org.springframework.security.config.Customizer.withDefaults;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;

@Configuration
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeHttpRequests((authz) -> authz
                .anyRequest().authenticated()
            )
            .httpBasic(withDefaults());
    }

    void unrelatedMethod() {} // <-- This is enough for the recipe to back off

}
```

That leaves a lot of projects which are not migrated, as it's not uncommon to add additional methods/beans in the same configuration file. For instance a [sample project here](https://github.com/timtebeek/spring-security-samples/blob/main/spring-cloud-gateway-oidc-tokenrelay/mock-flights-service/src/main/java/com/jdriven/flights/SecurityConfig.java#L21) merely adds a bean and changes the JWT converter, as [suggested in the official spring security documentation](https://docs.spring.io/spring-security/reference/5.7.2/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-claimsetmapping-rename). Yet the [restrictions in the recipe around applicable classes](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapter.java#L183) entirely skip this configuration class.

I'm not sure what the exact motivations were to play it safe, but it would seem to me we might want to loosen those restrictions just a bit to be workable for common cases.

**Comment by pway99** [comment]
Hello @timtebeek, 

I made an attempt https://github.com/openrewrite/rewrite-spring/pull/215 to relax the constraints per your suggestion and would appreciate your input.


cc: @BoykoAlex

**Comment by timtebeek** [comment]
Thanks for taking a look at this! Looked over the changes just now, and while I'm certainly no expert I'll add my thoughts here.

The thing that has me slightly worried is that the changes as they are right now take the recipe from very defensive, not making any potentially breaking change, to one that performs an incomplete migration. The markers do indicate that `userDetailsServiceBean`, `authenticationManagerBean` and `configure(AuthenticationManagerBuilder)` still need migration, but for people applying migrations in bulk those markers might be missed, leading to a broken application and potential loss of trust in bulk-applying-recipes.

What I would propose instead is to still back off whenever `userDetailsServiceBean`, `authenticationManagerBean` or `configure(AuthenticationManagerBuilder)` are found, but to still add markers there. That way the application remains working, albeit still using the deprecated `WebSecurityConfigurerAdapter`. The information is then there to guide people to a manual migration, still providing value in having run the recipe.

If none of the `userDetailsServiceBean`, `authenticationManagerBean` or `configure(AuthenticationManagerBuilder)` overrides are found, the recipe should be good to phase out `WebSecurityConfigurerAdapter`, even in the presence of other unrelated methods.

I think we're not far off from such an implementation, if you agree that this might be preferable to the current change proposal.

**Comment by pway99** [comment]
Thanks for taking the time to review the changes, I do agree the recipe should back off if the result would result in a breaking change, and have updated the recipe per your suggestions. :)

**Comment by timtebeek** [comment]
Perfect thanks! That makes this recipe useful even when it's not making functional changes. :)
Closing the issue now, unless you had something else you wanted to tag onto this one.

**Comment by pway99** [comment]
Nothing to tag on thanks Tim!
