### ISSUE TITLE
Invalid recipe reference: org.openrewrite.java.spring.boot2.SpringBootPropertiesManual_2_5

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-spring#220]
Looks like a missed detail from https://github.com/openrewrite/rewrite-spring/commit/f7e4ee05e2abe804f327476782f65a2164472a7d @tkvangorder 

`/src/main/resources/META-INF/rewrite/spring-boot-25.yml` references `org.openrewrite.java.spring.boot2.SpringBootPropertiesManual_2_5`, but that recipe seems to no longer exist.

https://github.com/openrewrite/rewrite-spring/search?q=org.openrewrite.java.spring.boot2.SpringBootPropertiesManual_2_5&type=code

Similar situation with 2.6: https://github.com/openrewrite/rewrite-spring/search?q=org.openrewrite.java.spring.boot2.SpringBootPropertiesManual_2_6&type=code

Maybe others too?

**Comment by tkvangorder** [comment]
Yeah, just an oversight when I cleaned these up, thanks @nmck257

**Comment by nmck257** [comment]
Cool -- this issue doesn't (didn't) affect functionality, right?
It spams the logs up a bit, but based on your fix, looks like all the recipes which were previously nested in those `...Manual...` recipes were already included in the stack somewhere else?
@tkvangorder
