### ISSUE TITLE
How to add @Component annotation to each class that have an @Inject annotation

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite-spring#222]
Hi,

I want to kwow how to have a "Go to class" in a visitor to  add @Component annotation for each class annoted with @Inject?

Is it possible?

Thanks

**Comment by tkvangorder** [comment]
@jdelobel The template is being used to convert a snippet of code (as text) into an abstract syntax tree. The parser used for this must be aware of any types that happen to appear in the template. By default, if you do not specify any type of classpath, the parser is only aware of types that exist in the Java runtime. 

So in this example, we need to make sure the parser used by the template has `javax.inject.Named` on its classpath to correctly type attribute the elements produced by the template.
