### ISSUE TITLE
Classes extending `HandlerInterceptorAdapter` can now directly implement `HandlerInterceptor`

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-spring#225]
Recipe to modify classes that extend `HandlerInterceptorAdapter` to implement the `HandlerInterceptor` interface instead.

There is also an `AsyncHandlerInceptor` interface and we will need to investigate when this interface should be used.

**Comment by pway99** [comment]
closed by https://github.com/openrewrite/rewrite-spring/commit/5a9fc2ecbbb01a24c2561b1b2ffdf1670322e785
