### ISSUE TITLE
Migration Recipe for Spring Security 6.0

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-spring#256]
The Spring Security team has produced a [migration guide for Spring Security 6.0](https://docs.spring.io/spring-security/reference/6.0.0/migration/index.html) that includes the following:

- [x] [remove `requireExplicitSave(true)`](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/session-management.html#_require_explicit_saving_of_securitycontextrepository) 
- [x] [Optimize Querying of RequestCache](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/session-management.html#requestcache-query-optimization) ([recipe](https://github.com/openrewrite/rewrite-spring/pull/327))
- [x] [Propagate AuthenticationServiceExceptions](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authentication.html#_propagate_authenticationserviceexceptions)
- [x] [Use SHA-256 in Remember Me](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authentication.html#servlet-opt-in-sha256-rememberme)
- [x] [Default authorities for oauth2Login()](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authentication.html#_default_authorities_for_oauth2login) ([recipe](https://github.com/openrewrite/rewrite-spring/pull/328))
- [x] [Use AuthorizationManager for Message Security](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authorization.html#_use_authorizationmanager_for_message_security) ([recipe](https://github.com/openrewrite/rewrite-spring/pull/330))
  - This is an XML only migration step (presumably for `beans.xml`)
- [x] [Use AuthorizationManager for Request Security](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authorization.html#_use_authorizationmanager_for_request_security) ([recipe](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/java/org/openrewrite/java/spring/security6/RemoveFilterSecurityInterceptorOncePerRequest.java))
- [x] [Use the new requestMatchers methods](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#use-new-requestmatchers)
- [x] [Add @Configuration to @Enable* annotations](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#_add_configuration_to_enable_annotations)

Reactive Migrations:
- [x] [Use AuthorizationManager for Method Security](https://docs.spring.io/spring-security/reference/6.0.0/migration/reactive.html#_use_authorizationmanager_for_method_security) ([recipe](https://github.com/openrewrite/rewrite-spring/pull/331))
- [x] [Propagate AuthenticationServiceExceptions](https://docs.spring.io/spring-security/reference/6.0.0/migration/reactive.html#_propagate_authenticationserviceexceptions)

**Comment by timtebeek** [comment]
Reading through these changes it seems to mostly involve cases where they changed the defaults, and then tell you how to remove the overrides of setting those defaults. That makes these recipes rather well to do compared to some other recipes, and perfect for individual contributors to pick up. Let us know if you need any help tackling one of these issues!

**Comment by knutwannheden** [comment]
@kunli2 Yes, let's close it. Thanks for noticing!
