### ISSUE TITLE
Error when using SpringBoot1To2Migration recipe

### ISSUE THREAD

**Issue by BlueIce** [openrewrite/rewrite-spring#259]
When running the `SpringBoot1To2Migration` recipe, errors are shown:
> [ERROR] Recipe validation error in org.openrewrite.java.spring.boot2.SpringBoot1To2Migration.recipeList[0] (in jar:file:/home/[redacted]/.m2/repository/org/openrewrite/recipe/rewrite-spring/4.31.0/rewrite-spring-4.31.0.jar!/META-INF/rewrite/spring-boot-2x.yml): recipe 'org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_0' does not exist.
> [ERROR] Recipe validation errors detected as part of one or more activeRecipe(s). Execution will continue regardless.

Could be related to commit cf6fe39548fc5e4d73e253751a13a84e72ac65d9 which changed the name of the recipe from `org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_0` to `org.openrewrite.java.spring.boot2.MigrateSpringBoot_2_0`.

### How to reproduce

1. Clone petclinic project: `git clone https://github.com/openrewrite/spring-petclinic-migration.git`
2. Run `SpringBoot1To2Migration`: `./mvnw org.openrewrite.maven:rewrite-maven-plugin:4.38.2:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:4.31.0 -DactiveRecipes=org.openrewrite.java.spring.boot2.SpringBoot1To2Migration`
3. Observe error messages in console

**Comment by tkvangorder** [comment]
@BlueIce Thank you for reporting, this was indeed related to that commit, we inadvertently changed the recipe ID.
