### ISSUE TITLE
update mysql-driver coordinates for Spring Boot 2.7.8

### ISSUE THREAD

**Issue by martinlippert** [openrewrite/rewrite-spring#274]
Upgrading projects to the latest version of Spring Boot 2.7 (`2.7.8`) is broken at the moment due to a missing artifact adjustment of the mysql driver:

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#mysql-jdbc-driver

**Comment by timtebeek** [comment]
Thanks again for reporting this one. Had the commit in #277 automatically close the issue, but feel free to reopen (or merely confirm fixed) based on your tests there.
