### ISSUE TITLE
Receipe for WebSecurityConfigurerAdapter deprecation not working if multiple such classes are defined

### ISSUE THREAD

**Issue by wimdeblauwe** [openrewrite/rewrite-spring#278]
I used the `org.openrewrite.java.spring.boot2.WebSecurityConfigurerAdapter` receipe for an application that uses multiple http security. You can view an example of such a setup in [the docs of an older version of Spring Security](https://docs.spring.io/spring-security/site/docs/5.0.0.RC1/reference/htmlsingle/#multiple-httpsecurity):

```
@EnableWebSecurity
public class MultiHttpSecurityConfig {
	@Bean                                                             
	public UserDetailsService userDetailsService() throws Exception {
		// ensure the passwords are encoded properly
		UserBuilder users = User.withDefaultPasswordEncoder();
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(users.username("user").password("password").roles("USER").build());
		manager.createUser(users.username("admin").password("password").roles("USER","ADMIN").build());
		return manager;
	}

	@Configuration
	@Order(1)                                                        
	public static class ApiWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
		protected void configure(HttpSecurity http) throws Exception {
			http
				.antMatcher("/api/**")                               
				.authorizeRequests()
					.anyRequest().hasRole("ADMIN")
					.and()
				.httpBasic();
		}
	}

	@Configuration                                                   
	public static class FormLoginWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http
				.authorizeRequests()
					.anyRequest().authenticated()
					.and()
				.formLogin();
		}
	}
}
```

The [newest version of the docs](https://docs.spring.io/spring-security/reference/5.7.0/servlet/configuration/java.html#_multiple_httpsecurity) shows how this should be done now:

```
@EnableWebSecurity
public class MultiHttpSecurityConfig {
	@Bean                                                             
	public UserDetailsService userDetailsService() throws Exception {
		// ensure the passwords are encoded properly
		UserBuilder users = User.withDefaultPasswordEncoder();
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(users.username("user").password("password").roles("USER").build());
		manager.createUser(users.username("admin").password("password").roles("USER","ADMIN").build());
		return manager;
	}

	@Bean
	@Order(1)                                                        
	public SecurityFilterChain apiFilterChain(HttpSecurity http) throws Exception {
		http
			.antMatcher("/api/**")                                   
			.authorizeHttpRequests(authorize -> authorize
				.anyRequest().hasRole("ADMIN")
			)
			.httpBasic(withDefaults());
		return http.build();
	}

	@Bean                                                            
	public SecurityFilterChain formLoginFilterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests(authorize -> authorize
				.anyRequest().authenticated()
			)
			.formLogin(withDefaults());
		return http.build();
	}
}
```

The receipe currently keeps the inner classes. The following logic should be implemented:

* The inner classes should be removed
* The `configure` methods that are now renamed to `filterChain` should be removed to something unique to avoid having multiple beans with the same name.
* Any `@Order` or `@Profile` annotations that are on the inner classes should be moved to the `filterChain` methods.
* In my cases, one of those inner classes also had a constructor that allowed to inject `Environment`. I had to change the `filterChain` method to also have this `Environment` as an extra parameter next to `HttpSecurity`. Not sure if that is feasible to automate, seems a bit complex.

**Comment by timtebeek** [comment]
Hi @wimdeblauwe ; thanks for the detailed example you've provided! It seems indeed that this case is not yet covered in [WebSecurityConfigurerAdapter](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapter.java) or [the associated tests](https://github.com/openrewrite/rewrite-spring/blob/main/src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterTest.java). 

The very least we could do there is add a marker when we're not quite sure whether we can fully automate this migration.

I know @BoykoAlex wrote the initial version of this migration script; perhaps he has some more insights here?

**Comment by BoykoAlex** [comment]
The recipe for `WebSecurityConfigurerAdapter` is rather limited. Only covers a few cases really. I was planning to circle back to this recipe (in ~2 weeks time) since Spring Security has the removal of `WebSecurityConfigurerAdapter` in Boot 3 as one of the top things for the Boot 3 migration from their side... I'll have a look at this once I'm back on this task

**Comment by timtebeek** [comment]
Awesome, thanks for staying involved and seeing it through for this use case as well; looking forward to it.

**Comment by BoykoAlex** [comment]
@wimdeblauwe I somehow suspect that the (newest version)[] has a typo - missing `@Configuration` next to `@EnableWebSecurity`. The javadoc for `EnableWebSecurity` has an example like this:
```
@Configuration
 @EnableWebSecurity
 public class MyWebSecurityConfiguration {

 	@Bean
 	public WebSecurityCustomizer webSecurityCustomizer() {
 		return (web) -> web.ignoring()
 		// Spring Security should completely ignore URLs starting with /resources/
 				.requestMatchers("/resources/**");
 	}

 ...

 }
 
```

In the light of this I think what we need to a visitor (or possibly a recipe) that flattens `@Configuration` classes. In other words if `@Configuration` annotated classes has inner classes annotated with the same `@Configuration` we may want to flatten the outer class by moving inner bean methods to the outer class and removing inner classes. This is the fix i have in mind.

**Comment by BoykoAlex** [comment]
@wimdeblauwe there is a PR attached. `@Order` annotation move from class to bean method in the general case is impossible to achieve. However, if having `@Order` annotation is important (perhaps some others) we could create a whitelist of such annotations and consequently have `@Order` annotation present as well.

**Comment by wimdeblauwe** [comment]
Thanks for working on this!
