### ISSUE TITLE
Bring Gradle dependency upgrades to parity with maven dependency upgrades

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-spring#288]
Anywhere we use a Maven recipe to bump a dependency we should have a corresponding gradle change.

**Comment by okundzich** [comment]
I remember jonathan mentioning https://github.com/openrewrite/rewrite-java-dependencies that could manage dependency recipes and delegate to maven or gradle.

**Comment by knutwannheden** [comment]
Should we add a new recipe to [openrewrite/rewrite-java-dependencies](https://github.com/openrewrite/rewrite-java-dependencies) in the scope of this issue already?

**Comment by knutwannheden** [comment]
@sambsnyd Would we now be in a good position to implement the buildtool-agnostic dependency upgrade recipe in [openrewrite/rewrite-java-dependencies](https://github.com/openrewrite/rewrite-java-dependencies)?

**Comment by timtebeek** [comment]
Picked up in https://github.com/openrewrite/rewrite-spring/commit/5e90a83ebedf970800cdb4719f46852bb132a40d
