### ISSUE TITLE
@ExtendWith and @ContextConfguration can be simplified to @SpringJUnitConfig

### ISSUE THREAD

**Issue by nbruno** [openrewrite/rewrite-spring#296]
Spring introduced the [`@SpringJUnitConfig`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/junit/jupiter/SpringJUnitConfig.html) annotation as a composed annotation for `@ExtendWith(SpringExtension.class)` and `@ContextConfiguration`. A recipe should be created to perform this migration.

The recipe should transform the following code:

    @ExtendWith(SpringExtension.class)
    @ContextConfiguration(classes = ExampleConfiguration.class)

Into:

    @SpringJUnitConfig(classes = ExampleConfiguration.class)

Note that `@SpringJUnitConfig` contains aliases for the following `@ContextConfiguration` attributes which should be maintained from the original `@ContextConfiguration` annotation when creating the `@SpringJUnitConfig` annotation:

- value
- classes
- locations
- initializers
- inheritLocations
- inheritInitializers
- name

It would be beneficial to also include this in the [migration from JUnit4 to JUnit5 recipe](https://docs.openrewrite.org/reference/recipes/java/spring/boot2/springboot2junit4to5migration), possibly as another step of the recipe that [removes unnecessary `@RunWith` annotations](https://docs.openrewrite.org/reference/recipes/java/spring/boot2/unnecessaryspringrunwith) or as a top-level recipe addition to the migration recipe.

**Comment by timtebeek** [comment]
Nice suggestion for another cleanup indeed!

**Comment by timtebeek** [comment]
Reopened as per the final comment on https://github.com/openrewrite/rewrite-spring/pull/297#issuecomment-1446408191. We want to try this out on a number of Spring projects through [public.moderne.io](https://public.moderne.io), so ensure there are no edge cases left uncovered before we hook this into the chain of upgrade recipes by default.

**Comment by timtebeek** [comment]
@nbruno I've just updated the platform to include your recipe: https://public.moderne.io/recipes/org.openrewrite.java.spring.boot2.ReplaceExtendWithAndContextConfiguration

When I run that recipe in isolation against 49 Spring projects, you get the following results: https://public.moderne.io/results/kfx9I
![image](https://user-images.githubusercontent.com/1027334/221602927-87c0b1e1-9fe8-4775-8820-c8f5aade9f72.png)

For the top one you can then create a fork, [as I've done](https://github.com/spring-projects/spring-data-jpa/compare/main...timtebeek:refactor/replace-extend-with-and-context-configuration-with-spring-junit-config?), to check that out and confirm it's working locally. Once confirmed you can then create a pull request to contribute back to Spring if you'd like.

Also let me know if you'd like me to include any of your own (public) projects in the platform to verify the recipe!

Once we have a decent sampling covered we can hook the recipe up for inclusion in the default migration chain, as discussed.

**Comment by timtebeek** [comment]
Confirmed to work locally for spring-data-jpa already: promising!
Won't open a pull request though as it's your work, not mine. :)

**Comment by nbruno** [comment]
Awesome! Opened the draft PR to enable this in the default migration chain. Feel free to submit PR's to the Spring repositories if it'd be beneficial for them.
