### ISSUE TITLE
RequestMapping paths should end with a trailing slash in spring 6 / spring-boot 3

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-spring#302]
As of spring 6 it has become necessary to explicitly include a trailing slash at the end of paths in `@RequestMapping` / `@GetMapping` / `@PostMapping` / etc. 

We should create a recipe that does this

**Comment by nmck257** [comment]
related: https://github.com/openrewrite/rewrite-spring/issues/257#issuecomment-1404160994

**Comment by knutwannheden** [comment]
I am not a Spring expert, but do we even know what the recipe should be doing? If we add the trailing slash to the annotations, doesn't that mean that the request paths without a trailing won't match anymore? Maybe we could just provide a recipe which can be optionally executed by the user, if that is what they want.

**Comment by timtebeek** [comment]
- Fixed in https://github.com/openrewrite/rewrite-spring/pull/307
