### ISSUE TITLE
why recipe SpringBoot1To2Migration removed

### ISSUE THREAD

**Issue by KaiqianYang** [openrewrite/rewrite-spring#305]
I find that org.openrewrite.java.spring.boot2.SpringBoot1To2Migration is removed in release 4.33.0. Could I ask why this recipe is removed? It seems a superset of UpgradeSpringBoot_2_7.

Should I stop using this recipe and use UpgradeSpringBoot_2_7 instead?

**Comment by timtebeek** [comment]
Hi @KaiqianYang ; `SpringBoot1To2Migration` was indeed removed in [this recent commit](https://github.com/openrewrite/rewrite-spring/commit/4b755e43015f275a945cd7e5d3235c9755ccdb61#diff-2a5424e861f8c0c2d6fddaaeae930cb9d199211c5e7afd0c6a951d47800d036c), in an effort to simplify the chaining of recipes and resolve a few issues we found. You should be fine using the replacement `UpgradeSpringBoot_2_7` instead.

Hope that helps!
