### ISSUE TITLE
Migration to Spring Boot 2.3 should maybe add spring-boot-starter-validation

### ISSUE THREAD

**Issue by jjank** [openrewrite/rewrite-spring#306]
I've tried to migrate Spring-Petclinic from before Boot 2.3 to the lastest Boot 2.7.x.

`ValidatorTests` fails because there is no Bean Validation provider on the classpath:
```
[INFO] Running org.springframework.samples.petclinic.model.ValidatorTests
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.079 s <<< FAILURE! - in org.springframework.samples.petclinic.model.ValidatorTests
[ERROR] shouldNotValidateWhenFirstNameEmpty  Time elapsed: 0.075 s  <<< ERROR!
javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at org.springframework.samples.petclinic.model.ValidatorTests.createValidator(ValidatorTests.java:24)
	at org.springframework.samples.petclinic.model.ValidatorTests.shouldNotValidateWhenFirstNameEmpty(ValidatorTests.java:36)
```

The [release-notes of Boot 2.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters) explain this change:

> As of [#19550](https://github.com/spring-projects/spring-boot/issues/19550), Web and WebFlux starters do not depend on the validation starter by default anymore. If your application is using validation features, for example you find that javax.validation.* imports are not being resolved, you’ll need to add the starter yourself.

In the Spring Boot 2.0 migration rewrite [adds the javax-validation-api](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-boot-20.yml#L130) as a maven dependency. But that does not solve the problem of a missing BV implementation starting from 2.3

What is probably needed is something in [/spring-boot-23.yml](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-boot-23.yml) along the lines of:

```yaml
  - org.openrewrite.maven.AddDependency:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-validation
      version: 2.3.x
      onlyIfUsing: javax.validation.constraints.*
```

I've tested that locally and it seems to resolve the problem. But I'm not sure if this is sufficient or if rewrite should check if an implementation of `hibernate-validator` is (transitively) available already?

**Comment by timtebeek** [comment]
I'd have sworn I didn't see those validation issues previously, but indeed I can't find any reference to an existing recipe step.
Sounds good adding that recipe into `spring-boot-23.yml`; with that `onlyIfUsing` also referenced in the docs.

If it's easy to check for transitive dependencies then that's welcome I suppose, if not we can err on the safe side and add this dependency as part of the 2.3 migration (only?).

**Comment by jjank** [comment]
> I'd have sworn I didn't see those validation issues previously, but indeed I can't find any reference to an existing recipe step.

Had a similar thought. I did this migration in November 2022 and I'm _quite_ sure that this problem did _not_ occur :shrug: 

> If it's easy to check for transitive dependencies then that's welcome I suppose
Not sure if it's easy. Shannon once suggested to use `DependencyInsight` to find transitive dependencies.

On the other hand: I think it is likely that most users will not have added a direct dependency on `hibernate-validator` but will have relied on the very fact that `spring-boot-starter-validation` was a transitive dependency of `spring-boot-starter-web` previously.  🤔

**Comment by timtebeek** [comment]
Yes quite likely that users need to add that dependency themselves, especially when using `javax.validation.*`. Are you eyeing up another contribution potentially? 😇

**Comment by timtebeek** [comment]
We have a test that uses a similar structure as what you're after here
https://github.com/openrewrite/rewrite-spring/blob/b5608dd01e45aba7c29f9618c5c595469c898774/src/testWithSpringBoot_2_4/java/org/openrewrite/maven/spring/UpgradeExplicitSpringBootDependenciesTest.java#L26-L127
You might need to add a classpath entry to the `spec` for the javax.validation imports & use, but other than that I think it should be manageable.

**Comment by jjank** [comment]
Thanks - that seems like a good starting point! Will give that a shot within the next weeks
