### ISSUE TITLE
SpringBoot1To2Migration recipe fail NoSuchMethodError UpgradeDependencyVersion.<init>

### ISSUE THREAD

**Issue by Martin-Office** [openrewrite/rewrite-spring#309]
I want to run SpringBoot1To2Migration recipe on my maven project.

``` xml
<plugin>
    <groupId>org.openrewrite.maven</groupId>
    <artifactId>rewrite-maven-plugin</artifactId>
    <version>4.42.0</version>
    <configuration>
        <activeRecipes>
            <recipe>org.openrewrite.java.spring.boot2.SpringBoot1To2Migration</recipe>
<!--        <recipe>org.openrewrite.java.testing.junit5.JUnit4to5Migration</recipe> -->
<!--        <recipe>org.openrewrite.java.spring.boot2.SpringBoot2JUnit4to5Migration</recipe> -->
<!--        <recipe>org.openrewrite.java.testing.mockito.Mockito1to3Migration</recipe> -->
        </activeRecipes>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-spring</artifactId>
            <version>4.29.0</version>
        </dependency>
<!--                     <dependency>-->
<!--                        <groupId>org.openrewrite</groupId>-->
<!--                        <artifactId>rewrite-maven</artifactId>-->
<!--                        <version>7.38.0</version>-->
<!--                    </dependency>-->
<!--                    <dependency>-->
<!--                        <groupId>org.openrewrite.recipe</groupId>-->
<!--                        <artifactId>rewrite-testing-frameworks</artifactId>-->
<!--                        <version>1.35.0</version>-->
<!--                    </dependency>
    </dependencies>
</plugin>
```

When I run

    mvn rewrite:dryRun

I get this result:

`Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.42.0:dryRun failed: java.lang.NoSuchMethodError: 'void org.openrewrite.maven.UpgradeDependencyVersion.<init>(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean)'`

What am I doing wrong? 
How can I fix this? 
Do I need to use an older version of the plugin or recipe?

**Comment by timtebeek** [comment]
Could you try this again using [rewrite-spring 4.34.0](https://github.com/openrewrite/rewrite-spring/releases/tag/v4.34.0) ?

**Comment by Martin-Office** [comment]
Thanks timtebeek, Your command works perfectly. 
I wasn't sure which recipe to choose. It's the first time I'm using openrewrite. 
Using command line is good since I do not need this plugin at the end of the migration.
Sadly the first recipe I use did not show this option. 
Would be good to have a comment on the recipe SpringBoot1To2Migration saying to look for the latest version of  UpgradeSpringBoot.

Thanks again for the quick answer!
Martin

**Comment by timtebeek** [comment]
Hi Martin, glad I could help! Sorry to hear you had some issues getting started;
I noticed just now that [one of our guides is outdated](https://github.com/openrewrite/rewrite-docs/issues/150), which will have thrown you off.
We'll get that sorted, and hope you enjoy working with OpenRewrite otherwise!
