### ISSUE TITLE
jaxb-runtime dependency after Spring Boot 3 migration

### ISSUE THREAD

**Issue by sergey-morenets** [openrewrite/rewrite-spring#321]
Hi

We ran Spring Boot 3 migration using rewrite-spring 4.34 and noticed new dependency in our pom.xml:

```
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>4.0.2</version>
			<scope>provided</scope>
		</dependency>
```

We don't use JAXB and XML at all in our project so why was this dependency added ?

**Comment by timtebeek** [comment]
Hi @sergey-morenets ! Sorry about those extra dependencies; that's likely already solved in https://github.com/openrewrite/rewrite-migrate-java/commit/f5e99fd2593395ffb97f4fc18769c60469511da3, but has not yet been released. If you want you can confirm the fix through [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions); you will want to use `rewrite-migrate-java:1.19.0-SNAPSHOT`. The log output will tell you exactly which recipes made changes to files, so if the problem reappears we would very much be interested in the log output to help track this down.

Hope you don't mind me closing this issue as likely-already-fixed. Feel free to reopen if still applicable, we certainly want to know if it's not been fixed!
