### ISSUE TITLE
Spring Boot 3 Migration does not work with Petclinic repository

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-spring#323]
<@U04EXGVQX1Q> Re Spring Petclinic and OpenRewrite. 

I checked out [this repo](https://github.com/openrewrite/spring-petclinic-migration) with the `2.1.x` branch. I then updated the `build.gradle` file to have:

A plugin of:
```id 'org.openrewrite.rewrite' version '5.38.0'```

A rewrite section of:

```
rewrite {
    activeRecipe("org.openrewrite.java.cleanup.CommonStaticAnalysis")
    activeRecipe("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0")
}
```

And dependencies of:

```
rewrite(platform("org.openrewrite.recipe:rewrite-recipe-bom:1.17.0"))
rewrite("org.openrewrite.recipe:rewrite-spring")
```

Running the `rewriteDryRun` task results in a `Index 0 out of bounds for length 0` error. Please let me know if there's anything else I can provide you with

[Slack Message](https://moderneinc.slack.com/archives/C01VADFPJQZ/p1679938234758379?thread_ts=1679938234.758379&cid=C01VADFPJQZ)

**Comment by knutwannheden** [comment]
@kunli2 I made a fix here, but I don't know if it fixes this issue or not: https://github.com/openrewrite/rewrite-spring/commit/acce0abedb4df65f4bbeeaaec559f0ec5ac28b3d

**Comment by kunli2** [comment]
@knutwannheden , I verified and confirm it's fixed now.
Thanks for the fixing.
