### ISSUE TITLE
Recipe for boot 2.2 change where charset attribute dropped from JSON content type headers

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#33]
As of spring-boot 2.2 the charset attribute was dropped from the content type headers
[major browsers like Chrome now comply with the specification and interpret correctly UTF-8 special characters without requiring a charset=UTF-8 parameter](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON_UTF8)

convert:
```
ResultActions actions = mockMvc.perform(get("/vets.json")
     .accept(MediaType.APPLICATION_JSON))
     .andExpect(status().isOk());
actions.andExpect(content().contentType("application/json;charset=UTF-8"));
```
to:
```
 ResultActions actions = mockMvc.perform(get("/vets.json")
     .accept(MediaType.APPLICATION_JSON))
     .andExpect(status().isOk());
actions.andExpect(content().contentType("application/json"));
```

**Comment by sambsnyd** [comment]
The impact of this seems quite low. It isn't problematic to explicitly include UTF-8 in the content-type header, so the upside of creating this recipe seems minor.
