### ISSUE TITLE
Simplify unnecessary MediaType.parse calls

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-spring#337]
> ```java
> MediaType.parse("application/json")
> // Could instead be
> MediaType.APPLICATION_JSON
> ```

As discussed in: https://github.com/openrewrite/rewrite-spring/issues/325#issuecomment-1508284641

**Comment by timtebeek** [comment]
Good to track this separately; we might also want to include the case where a `MediaType` constant is used as a value, since we're migrating users towards that as of #325
