### ISSUE TITLE
Validate rewrite-spring against various public repositories

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#36]
Repositories and projects passing validation
- [ ] spring-cloud-openfeign
- [ ] spring-cloud-netflix-core

**Comment by okundzich** [comment]
Please also add a list of repos that pass validation

**Comment by pway99** [comment]
- [X] ConditionalOnAnyBean bug #34

**Comment by pway99** [comment]
Closing this issue in favor of working discovered issues individually
