### ISSUE TITLE
Incomplete changes for Sleuth migration recipe  with SpringBoot 3

### ISSUE THREAD

**Issue by sjungling** [openrewrite/rewrite-spring#364]
Nothing happens when running  `org.openrewrite.java.spring.cloud2022.MigrateCloudSleuthToMicrometerTracing` 

 
The simplest case of using `spring-cloud-starter-sleuth` is just adding this dependency to a Spring Boot application and we start to see traces and spans in the logs.
 
The steps below are required to see traces and spans in the logs in a Spring Boot 3 application :
 
When we are using a spring boot 3, we should add the actuator dependency if not present because this is where the autoconfiguration takes place :

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```
 
Source : https://www.baeldung.com/spring-boot-3-observability#1-actuator
 
To replace `spring-cloud-sleuth` dependency, we need to add this dependency (Spring Boot manages the version) :
 
```
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-tracing-bridge-brave</artifactId>
</dependency>
```

This was set automatically with Spring Cloud Sleuth but now we have to set it manually :
 
If there is an application.yaml (or application.yml), add this :

```
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
```

Else if there is an application.properties, add this :

``` 
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
```
 
Source : https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#log-pattern

**Comment by rpau** [comment]
@timtebeek Could you confirm that:

- [ ] When we are using a spring boot 3, we should add the actuator dependency
- [ ] Replace `spring-cloud-sleuth` for `io.micrometer: micrometer-tracing-bridge-brave`
- [ ] Add the logging level in the `application.yaml`.
- [ ] Add the logging level in the `application.properties`

**Comment by timtebeek** [comment]
Yes; all of those are covered in [META-INF/rewrite/spring-cloud-2022.yml](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-cloud-2022.yml) :)

**Comment by rpau** [comment]
Thanks @timtebeek !

I am marking this ticket as closed until we know is there a particular case that it is not covered.

**Comment by okundzich** [comment]
@sjungling, there was an email from Remy asking for this. Can we send him a response there saying we completed this perhaps connecting to @timtebeek for direct feedback?
