### ISSUE TITLE
Plugin versions are not adapted for gradle UpgradeSpringBoot

### ISSUE THREAD

**Issue by Jenson3210** [openrewrite/rewrite-spring#374]
## What version of OpenRewrite are you using?
I am using Gradle plugin 6.0.0

## How are you running OpenRewrite? 

- Gradle plugin
- [a7439c7 commit of spring-petclinic](https://github.com/spring-projects/spring-petclinic/tree/a7439c74ea718c4f59fe6c7c643c4afe59d7e718) as this is the first commit with gradle on petclinic repo

Can you share your configuration so that we can rule out any configuration issues? 

- gradle 7.4
- MAC OS

### Adapt build gradle to run rewrite: 
```groovy
plugins {
  id 'org.springframework.boot' version '2.6.1'
  id 'io.spring.dependency-management' version '1.0.11.RELEASE'
  id 'java'
  id 'org.openrewrite.rewrite' version '6.0.0'
}

rewrite {
    activeRecipe(
            'org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0',
    )
}

//...
dependencies {
  rewrite platform('org.openrewrite.recipe:rewrite-recipe-bom:2.0.0')
  rewrite('org.openrewrite.recipe:rewrite-spring')
  ...
}
```

### Run openrewrite

Launch `gradle rewriteRun`. 
Wait for build succeeded message.

**Expected behaviour**

Plugin versions are adapted

**Actual behaviour**

Plugin versions are not adapted
```groovy
plugins {
  id 'org.springframework.boot' version '2.6.1' // <-- Version not adapted
  id 'io.spring.dependency-management' version '1.0.11.RELEASE' // <-- Version not adapted
  //...
}
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Sure, if guided properly I am always open to take "newbie" tickets!

**Comment by knutwannheden** [comment]
@Jenson3210 Thanks for your report! The OpenRewrite Spring recipes only recently started supporting Gradle-based projects, so we are very glad to receive feedback in any form regarding this.
