### ISSUE TITLE
mysql-connector-java should use generic ChangeDependency over maven specific one

### ISSUE THREAD

**Issue by Jenson3210** [openrewrite/rewrite-spring#375]
## What version of OpenRewrite are you using?
I am using Gradle plugin 6.0.0

## How are you running OpenRewrite? 

- Gradle plugin
- [a7439c7 commit of spring-petclinic](https://github.com/spring-projects/spring-petclinic/tree/a7439c74ea718c4f59fe6c7c643c4afe59d7e718) as this is the first commit with gradle on petclinic repo

Can you share your configuration so that we can rule out any configuration issues? 

- gradle 7.4
- MAC OS

### Adapt build gradle to run rewrite: 
```groovy
plugins {
  id 'org.springframework.boot' version '2.6.1'
  id 'io.spring.dependency-management' version '1.0.11.RELEASE'
  id 'java'
  id 'org.openrewrite.rewrite' version '6.0.0'
}

rewrite {
    activeRecipe(
            'org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0',
    )
}

//...
dependencies {
  rewrite platform('org.openrewrite.recipe:rewrite-recipe-bom:2.0.0')
  rewrite('org.openrewrite.recipe:rewrite-spring')
  ...
}
```

### Run openrewrite

Launch `gradle rewriteRun`. 
Wait for build succeeded message.

**Expected behaviour**

`mysql:mysql-connector-java` is replaced with `mysql-connector-j` as it is for [maven](https://github.com/openrewrite/rewrite-spring/blob/f0151affbff68d4c6538540ae4fe605ecabc0c2e/src/main/resources/META-INF/rewrite/spring-boot-27.yml#L54-L59)

**Actual behaviour**

It is not changed.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Sure, if guided properly I am always open to take "newbie" tickets!

**Comment by Jenson3210** [comment]
@timtebeek as mentioned, I will try to find some time for this one as it appears trivial indeed!

**Comment by timtebeek** [comment]
> as mentioned, I will try to find some time for this one as it appears trivial indeed!

Much appreciated! Let me know if you need any help; It's usually best to start with a unit test, which we should already have some samples for in this repository, and then work from there. Also welcome to reach out on [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if that helps!
