### ISSUE TITLE
Spring Security 6.x removed `@Configuration` meta-annotation from `@Enable*` annotations

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#387]
## What problem are you trying to solve?
Before https://github.com/spring-projects/spring-security/commit/040111ae9e8dc830973863eca3ac9d5b1c2c2976 the Spring Security  Enable* annotations were meta annotated with `@Configuration`, such that it was not necessary to additionally annotate classes using those annotations with `@Configuration`.

## What precondition(s) should be checked before applying this recipe?
As this has been dropped in the move to Spring Security 6.x, it might be best to introduce this annotation for any projects on Spring Security 5.x, before the subsequent upgrade to 6.x.

I'd hold off from adding this annotation when already on 6.x, because of the changed semantics, but anyone is welcome to challenge me on that.

## Describe the situation before applying the recipe

```java
@EnableGlobalAuthentication
class A {
}
@EnableGlobalMethodSecurity
class B {
}
@EnableMethodSecurity
class C {
}
@EnableReactiveMethodSecurity
class D {
}
@EnableWebSecurity
class E {
}
```

## Describe the situation after applying the recipe

```java
@Configuration
@EnableGlobalAuthentication
class A {
}
@Configuration
@EnableGlobalMethodSecurity
class B {
}
@Configuration
@EnableMethodSecurity
class C {
}
@Configuration
@EnableReactiveMethodSecurity
class D {
}
@Configuration
@EnableWebSecurity
class E {
}
```

## Have you considered any alternatives or workarounds?
No really. I'd think a recipe is the best approach here.

## Any additional context
https://github.com/spring-projects/spring-security/issues/6613
https://github.com/spring-projects/spring-security/pull/11653

**Comment by nmck257** [comment]
Regarding preconditions, I'd probably check that no other annotations already present on the class provide `@Configuration` as a meta-annotation, such as `@SpringBootApplication` (except for the Enable annotations which inspired this card in the first place)

Regarding 5.x vs 6.x -- I'd probably place this recipe at the version where spring made the change, or at the version where they announced that this change is coming (assuming they did). And I wouldn't worry too much about this recipe running on projects which are already 6.x, as an enable annotation without a configuration annotation at that point is very likely an error anyway

**Comment by BoykoAlex** [comment]
Shouldn't this recipe handle most of these cases:
https://github.com/openrewrite/rewrite-spring/blob/main/src/main/java/org/openrewrite/java/spring/boot3/ConfigurationOverEnableSecurity.java
(Tests are here and are more descriptive perhaps:  https://github.com/openrewrite/rewrite-spring/blob/main/src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/ConfigurationOverEnableSecurityTest.java)
