### ISSUE TITLE
gradle wrapper update included in the spring boot migration

### ISSUE THREAD

**Issue by rpau** [openrewrite/rewrite-spring#392]
## What problem are you trying to solve?

Update a gradle project automatically to Spring Boot 3

## Describe the solution you'd like

Update the gradle wrapper in the migration.

**Comment by shanman190** [comment]
Just a note, but this is just reverting these two commits.

https://github.com/openrewrite/rewrite-spring/commit/9001bf170603b0f20f774a071348040bdcdc72e2
https://github.com/openrewrite/rewrite-spring/commit/72ae241cd2c734e5ef478950720b9890c16e4718
