### ISSUE TITLE
Remove import from RemoveEnableBatchProcessing recipe

### ISSUE THREAD

**Issue by alexpm-14** [openrewrite/rewrite-spring#406]
Hello, I am using these versions

- Maven plugin v5.2.2
- rewrite-spring v5.0.1

I am using the Maven plugin with my own recipes, which include RemoveEnableBatchProcessing, and i've found this recipe doesn't remove the @EnableBatchProcessing import, causing a QA issue.

Its own test checks that it's not removing the import (https://github.com/openrewrite/rewrite-spring/blob/main/src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/RemoveEnableBatchProcessingTest.java)

Should this recipe remove this import instead of depending of other recipes to remove imports?

**Comment by timtebeek** [comment]
@alexpm-14 Thanks for bringing this to our attention! Not removing the import made no sense; fixed now in 5514dc5be82ecba1137ee1d4cca58ffe9b7999fc, which will likely see a release in the next few days. Until then you can use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions).

**Comment by alexpm-14** [comment]
Great to see this quick fix, thank you!

**Comment by timtebeek** [comment]
No problem! Had considered asking if you'd like to contribute, but figured that you'd prefer a quick fix. Feel free to directly open a pull request if you spot any other issues though!
