### ISSUE TITLE
Validate JUnit 4 to 5 migration on Spring 2.x repositories

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-spring#41]
Migration to Spring Boot 2.4 requires migration to JUnit 5. Prior version of Spring Boot 2.x could continue to use JUnit 4. This create an urgent need to move JUnit 4 to 5, but limits the scope of applicable Spring recipes. Spring 1.x to 2.x recipes are not required for this transition.

Create another yaml recipe in rewrite-spring that only packages necessary recipes for this JUnit 4 to 5 migration for repositories already on Spring 2.x. Let's validate this recipe and produce a list of repos that pass validation.

**Comment by pway99** [comment]
Import layout style groups nested classes https://github.com/openrewrite/rewrite/issues/352

**Comment by pway99** [comment]
closing this in favor of working identified issues
