### ISSUE TITLE
Spring Boot 3 - Upgrade to Spring Doc OpenApi 2

### ISSUE THREAD

**Issue by Mistborn94** [openrewrite/rewrite-spring#430]
## What problem are you trying to solve?

When upgrading to Spring Boot 3, [SpringDoc OpenApi](https://springdoc.org/) needs to be upgraded to 2.x. 

The upgrade includes version changes, changed / removed dependencies and code changes
Upgrade guide from SpringDoc https://springdoc.org/#migrating-from-springdoc-v1 

## What precondition(s) should be checked before applying this recipe?

This recipe should only execute if there are springdoc dependencies on the classpath

## Describe the situation after applying the recipe

Dependency and code changes like described in the upgrade guide 

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?

Yes, I can contribute it. I have most of it already from implementing it for my own projects.

**Comment by timtebeek** [comment]
Glad to hear you're open to contributing! Feel free to open a PR, even as draft, and we'll see what it needs to get merged

**Comment by Mistborn94** [comment]
Pull request up :)

**Comment by timtebeek** [comment]
Thanks so much for adding these migration recipes! Great help in getting users migrated. Looked straightforward too; wonder if it would make sense to add your recipe to their migration docs. 🤔
