### ISSUE TITLE
Spring JUnit 4 to 5 ModifiedClassPathRunner to ModifiedClassPathExtension

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#45]
The JUnit5 variant of the SpringBoot ModifiedClassPathRunner is ModifiedClassPathExtension.

Add declarative `org.openrewrite.java.testing.junit5.RunnerToExtension` to the `org.openrewrite.java.spring.Boot2JUnit4to5Migration` recipe

**Comment by pway99** [comment]
this one it will require some additional research and may even turn out to be a low priority issue

**Comment by pway99** [comment]
rewrite modifies the class and adds the spring-boot-tools dependency; however, the 
`ModifiedClassPathExtension;` symbol cannot be resolved
for:
https://github.com/spring-cloud/spring-cloud-commons/blob/8ff619676d6484a49200e42e49f57f9d470453df/spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/ServiceRegistryAutoConfigurationTests.java#L35

```
...
import org.springframework.boot.testsupport.runner.classpath.ModifiedClassPathExtension;
...
@ExtendWith(ModifiedClassPathExtension.class)
@ClassPathExclusions({"spring-boot-actuator-*.jar", "spring-boot-starter-actuator-*.jar"})
public class ServiceRegistryAutoConfigurationTests {
```
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-tools</artifactId>
	<version>2.2.13.RELEASE</version>
	<scope>test</scope>
</dependency>
```

**Comment by pway99** [comment]
spring-cloud-commons ModifiedClassPathRunner should not be replaced with the spring-boot-tools ModifiedClassPathRunner
https://github.com/spring-cloud/spring-cloud-commons/blob/8ff619676d6484a49200e42e49f57f9d470453df/spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ModifiedClassPathRunner.java#L71

**Comment by tkvangorder** [comment]
So after some more investigation: 

In Spring Boot, the ModifiedClassPathExtension is actually package-private and this extension is added via `ClassPathOverrides` and `ClassPathExclusions` which both include an `ExtendsWith(ModifieidClassPathExtension.class)`

So the correct behavior is to just remove the old runner.

As for the version in spring-cloud-commons, after talking a bit with Spencer, there is not yet a comparable ModifiedClassPathExtension class, so there is really nothing we can do at this time.
