### ISSUE TITLE
JUnit 4 to 5 OutputCaptureRule to OutputCaptureExtension

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#46]
The JUnit 5 variant of OutputCaptureRule is OutputCaptureExtension.  

1. Add declarative org.openrewrite.java.testing.junit5.RunnerToExtension to the org.openrewrite.java.spring.Boot2JUnit4to5Migration recipe
2. convert the any `OutputCaptureRule` usages to there `OutputCaptureExtension` variant 

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/system/OutputCaptureExtension.html

**Comment by pway99** [comment]
`org.junit.jupiter.api.extension.ExtendWith` import not added to imports

after:
```
package org.springframework.cloud.configuration;

import org.assertj.core.api.BDDAssertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.BeanCreationException;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.system.OutputCaptureExtension;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.NestedExceptionUtils;

import static org.assertj.core.api.BDDAssertions.then;
...
@ExtendWith(OutputCaptureExtension.class)
public class CompatibilityVerifierFailureAutoConfigurationTests 
```

https://github.com/spring-cloud/spring-cloud-commons/blob/8ff619676d6484a49200e42e49f57f9d470453df/spring-cloud-commons/src/test/java/org/springframework/cloud/configuration/CompatibilityVerifierFailureAutoConfigurationTests.java#L35-L38

**Comment by aegershman** [comment]
not to pester but is this closed by https://github.com/openrewrite/rewrite-spring/blob/master/src/main/java/org/openrewrite/java/spring/boot2/OutputCaptureExtension.java ?
