### ISSUE TITLE
spring-boot-23 recipe is not rewriting OutputCapture to OutputCaptureRule

### ISSUE THREAD

**Issue by FieteO** [openrewrite/rewrite-spring#472]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v5.18.0
- rewrite-spring v5.1.7

## How are you running OpenRewrite?

I am using the Maven command line invokation
```bash
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_3
```

## What is the smallest, simplest way to reproduce the problem?

```java
import org.springframework.boot.test.rule.OutputCapture;

public class MyTest {
    @Rule
    public OutputCapture capture = new OutputCapture();
}
```

## What did you expect to see?

```java
import org.springframework.boot.test.system.OutputCaptureRule;

public class MyTest {
    @Rule
    public OutputCaptureRule capture = new OutputCaptureRule();
}
```

## What did you see instead?

No change, such that the code remains as before:  
```java
import org.springframework.boot.test.rule.OutputCapture;

public class MyTest {
    @Rule
    public OutputCapture capture = new OutputCapture();
}
```

## What is the full stack trace of any errors you encountered?

No errors.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I currently lack the time to do so unfortunately.

**Comment by timtebeek** [comment]
Thanks for reporting this here! Looks like this might be all we need:
- https://github.com/openrewrite/rewrite-spring/pull/473

Let me know what you think, or if I've missed anything.

**Comment by timtebeek** [comment]
Glad that helps ; you can try it out through [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions) soon after the build completes. It will be in the next version in two to three weeks.
