### ISSUE TITLE
@Autowired is removed when there is an additional @NoArgsConstructor

### ISSUE THREAD

**Issue by timo-abele** [openrewrite/rewrite-spring#479]
## What version of OpenRewrite are you using?

I am using

- Maven/Gradle plugin v5.8.0
- rewrite-spring v5.3.0

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
    <artifactId>rewrite-maven-plugin</artifactId>
    <configuration>
        <activeRecipes>
            <recipe>org.openrewrite.java.spring.NoAutowiredOnConstructor</recipe>
        </activeRecipes>
    </configuration>
    <dependencies>
        <dependency>
            <artifactId>rewrite-spring</artifactId>
            <groupId>org.openrewrite.recipe</groupId>
            <version>5.3.0</version>
        </dependency>
    </dependencies>
    <groupId>org.openrewrite.maven</groupId>
    <version>5.18.0</version>
</plugin>
```

## Problem Description

Per https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/using-boot-spring-beans-and-dependency-injection.html 

> If a bean has one constructor, you can omit the @Autowired

Currently however, this recipe also removes the @Autowired if there are two constructors, namely one explicit, and one @NoArgsConstructor via lombok.
(In my case the app did still start up but there was an error in the tests.)
I haven't looked at the recipe, the other lombok constructors or multiple constructors in general might also be overlooked.

## What is the smallest, simplest way to reproduce the problem?

This is a sketch, but I hope it gets the point accross.

```java
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@NoArgsConstructor
public class AService {

  private FooMapper fooMapper;

  @Autowired
  public AService(FooMapper fooMapper) {
    this.fooMapper = fooMapper;
  }
}
```

## What did you expect to see?

no change

## What did you see instead?

```java
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@NoArgsConstructor
public class AService {

  private FooMapper fooMapper;

  public AService(FooMapper fooMapper) {
    this.fooMapper = fooMapper;
  }
}
```

## What is the full stack trace of any errors you encountered?

```
stacktrace output here
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

no

**Comment by timtebeek** [comment]
Thanks for the report! Indeed a case not yet covered, but I think it should be trivial to add. Some context.

Right now we already detect existing constructors, but this check does not yet include lombok annotations.
https://github.com/openrewrite/rewrite-spring/blob/b76e03437143632ec9d42ffc0a5e7af2b88f11c9/src/main/java/org/openrewrite/java/spring/NoAutowiredOnConstructor.java#L53-L61

We do already check for other annotations to skip making changes though; so it should be trivial to check for Lombok annotation arguments too.
https://github.com/openrewrite/rewrite-spring/blob/b76e03437143632ec9d42ffc0a5e7af2b88f11c9/src/main/java/org/openrewrite/java/spring/NoAutowiredOnConstructor.java#L63-L66

That makes this a good first issue for anyone to pick up.

**Comment by timtebeek** [comment]
Notice you had indicated you weren't interested to contribute; that's fine. I found a spare moment on a call to resolve this one for you. Should be in the next release in a week or two, but you can already try it out from [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions)
