### ISSUE TITLE
JUnit 4 to 5 Mockito cannot mock  org.springframework.cloud.commons.util.InetUtils

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#48]
Discovered while testing spring-cloud-slueth-zipkin 2.0.x:

Mockito cannot mock InetUtils.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/e36e75fdafa5b42087ce6483545cf7335a63649d/spring-cloud-sleuth-zipkin/src/test/java/org/springframework/cloud/sleuth/zipkin2/DefaultEndpointLocatorConfigurationTest.java#L222-L227

**Comment by sambsnyd** [comment]
So... what are we supposed to do about that? Unclear what the action for us is here.
