### ISSUE TITLE
Spring migration removes Lombok imports

### ISSUE THREAD

**Issue by sergeykad** [openrewrite/rewrite-spring#489]
## What version of OpenRewrite are you using?

I am using Gradle init script

## How are you running OpenRewrite?

I am using the Gradle init script, and my project is a multi-module project.
```gradle
initscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2" }
    }
    dependencies { classpath("org.openrewrite:plugin:6.8.0") }
}
rootProject {
    plugins.apply(org.openrewrite.gradle.RewritePlugin)
    dependencies {
        rewrite("org.openrewrite.recipe:rewrite-spring:5.3.1")
    }
    rewrite {
        activeRecipe("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2")
    }
    afterEvaluate {
        if (repositories.isEmpty()) {
            repositories {
                mavenCentral()
            }
        }
    }
}
```

## What is the smallest, simplest way to reproduce the problem?

Run the Spring 3.2 migration on Java code that contains `import lombok.*;`

## What did you expect to see?
The Lombok imports have not changed.

## What did you see instead?

Lombok imports that include asterisk are removed

## What is the full stack trace of any errors you encountered?
None

## Are you interested in [contributing a fix to OpenRewrite]
No

**Comment by timtebeek** [comment]
Hi! This was a bug solved in v6.8.1 of the gradle plugin:
https://github.com/openrewrite/rewrite-gradle-plugin/releases/tag/v6.8.1

Hope that helps! I'm closing this issue already as it's come up before, but will monitor for your reply to be sure you've got things working. :)
