### ISSUE TITLE
Migration recipe for deprecated spring-boot-test EnvironmentTestUtils 

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#49]
Discovered while testing spring-cloud-slueth-zipkin 2.0.x.

org.springframework.boot.test.util.EnvironmentTestUtils is deprecated

**Comment by kmccarp** [comment]
Recreated here: https://github.com/kmccarp/spring-cloud-sleuth/commit/b63f3993e8baef7fe0fdf906f5f8b325f112b323#diff-21cdd2981ca0ed6276a5603339d5bfa6827ddf146f523b694b0d83db3301ed8c

**Comment by aegershman** [comment]
not to pester, but is this closed by virtue of https://github.com/openrewrite/rewrite-spring/blob/master/src/main/java/org/openrewrite/java/spring/boot2/ReplaceDeprecatedEnvironmentTestUtils.java ? (/cc @kmccarp )

**Comment by kmccarp** [comment]
Yes, good catch! Closing.
