### ISSUE TITLE
UpgradeSpringBoot_3_2 recipe for Kotlin

### ISSUE THREAD

**Issue by sk-saha** [openrewrite/rewrite-spring#498]
## What problem are you trying to solve?
Upgrade Kotlin Spring Boot projects to 3.2.x

## Have you considered any alternatives or workarounds?
org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
Did not really work.

**Comment by timtebeek** [comment]
Hi! Sorry to hear about your issues; I'm lacking the required details to help your troubleshoot though; could you reply here with the details asked in this form? https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by AnkitaJain06** [comment]
facing the same issue 
org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
Did not really work to upgrade Kotlin Spring Boot projects to 3.2.x

**Comment by timtebeek** [comment]
What commands did you run? What output did you see?
We have a template that helps us reproduce, until then we can't do much:
https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by AnkitaJain06** [comment]
I have added my issue in this template
https://github.com/openrewrite/.github/compare/main...AnkitaJain06:.github:patch-1

**Comment by AnkitaJain06** [comment]
Can we have support for spring in Kotlin projects by open rewrite?

**Comment by nmck257** [comment]
The spring recipes *can* be run on Kotlin projects, and many parts of the recipe should work just fine. So if you see something wrong when trying the recipe, then this is a bug report, not a feature request.

And as @timtebeek suggested (multiple times), for a bug report, we need detail. And this template asks for exactly the kind of details needed: https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

(you can paste the template content into a comment here instead of doing a fork+PR, if that's easier)

**Comment by AnkitaJain06** [comment]
I have raised the issue
https://github.com/openrewrite/.github/pull/9

---
name: Issue with Kotlin spring version upgrade to 3.2.x
about: open-rewrite working on Groovy but not with Kotlin DSL
title: ' '
labels: 'bug'
assignees: ' '
---
## What version of OpenRewrite are you using?
I am using
- OpenRewrite v6.10.0
- Gradle plugin both Groovy and Kotlin DSL
- org.openrewrite.recipe:rewrite-spring:5.7.0
## How are you running OpenRewrite?
I am using the gradle plugin for both Groovy and Kotlin DSL
```xml
plugins {
    id("org.openrewrite.rewrite") version("6.10.0")
}
rewrite {
    activeRecipe("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2")
}
repositories {
    mavenCentral()
}
dependencies {
    rewrite("org.openrewrite.recipe:rewrite-spring:5.7.0")
}
```
## What did you expect to see?
While running the above recipe I am expecting spring version update changes in build.gradle.kts / build.gradle. The expected changes take place when the kotlin repo has build.gradle but the expected changes don't take place when kotlin repo has build.gradle.kts.
```xml
# build.gradle.kts 
plugins {
id ("org.springframework.boot") version "3.2.3"
}
```
## What did you see instead?
No changes in build.gradle.kts file.

```xml
# build.gradle.kts 
plugins {
id ("org.springframework.boot") version "3.1.3"
}
```

**Comment by timtebeek** [comment]
Gradle KTS files are not yet supported, which is why you're not yet seeing results. Other Kotlin files should be updated if needed

**Comment by timtebeek** [comment]
I'm going to closev this issue over a lack of actionable details. It's unclear what the original poster was asking, and the follow up here only led to a known item we have not implemented yet.
