### ISSUE TITLE
How to change types of different versions of a library

### ISSUE THREAD

**Issue by rbosse** [openrewrite/rewrite-spring#5]
Hi,

We are migration from different versions of Spring Boot.  I would like to be able to change type 
org.springframework.boot.web.support.SpringBootServletInitializer
to
org.springframework.boot.web.servlet.support.SpringBootServletInitializer

(From Spring Boot 1.5 to Spring Boot 2.2).

Is it possible to do that ?

Thanks

**Comment by jkschneider** [comment]
Note also that there was an issue with declarative rule execution fixed in https://github.com/openrewrite/rewrite/issues/3 that this depends on.
