### ISSUE TITLE
UpgradeSpringBoot_3_0 Dropwizard metric-servlet(s) dependencies need to be renamed

### ISSUE THREAD

**Issue by timo-abele** [openrewrite/rewrite-spring#506]
## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.23.1</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-spring</artifactId>
                        <version>5.5.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## What is missing?

Dropwizard offers separate packages for jakarta, so as part of the migration to spring boot 3

```xml
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-servlets</artifactId>
    </dependency>
```
must become
```xml
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-jakarta-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-jakarta-servlets</artifactId>
    </dependency>
```
the packages change as well, so e.g.

```java
import com.codahale.metrics.servlet.InstrumentedFilter;
import com.codahale.metrics.servlets.MetricsServlet;
```
must become
```java
import io.dropwizard.metrics.servlet.InstrumentedFilter;
import io.dropwizard.metrics.servlets.MetricsServlet;
```

That's all I had to do :-)

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

no

**Comment by timtebeek** [comment]
Thanks for the report! Indeed looks like a step not yet covered, but reasonably easy to add by [composing recipes in our builder](https://app.moderne.io/recipes/builder). I'm thinking

1.  [Rename package name](https://docs.openrewrite.org/recipes/java/changepackage) for
  a. `com.codahale.metrics.servlet` to `com.codahale.metrics.servlets`
  b. `io.dropwizard.metrics.servlet` to `io.dropwizard.metrics.servlets`
2. [Change Maven managed dependency groupId, artifactId and optionally the version](https://docs.openrewrite.org/recipes/maven/changemanageddependencygroupidandartifactid) for
  a. `metrics-servlet` to `metrics-servlets`
  b. `metrics-jakarta-servlet` to `metrics-jakarta-servlets`

To be stuck into [rewrite-spring/src/main/resources/META-INF/rewrite/spring-boot-30.yml](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-boot-30.yml), likely as a separate named recipe similar to what we did for `org.openrewrite.java.spring.boot3.MigrateThymeleafDependencies`.

That makes this a good first issue that anyone is welcome to pick up.

**Comment by timtebeek** [comment]
Hi & thanks for the offer to help! Feel free to open a draft pull request early that links to this issue and we'll then assign the issue to you.

**Comment by bsmahi** [comment]
Hi @timtebeek 

Thanks :)

If you don't mind, could you please let me know where to start, because this is first time am working on open-rewrite issues
hence your guidance is greatly appreciated. Next time onwards, I will pull it up.
Thanks,
Mahendra

**Comment by bsmahi** [comment]
@timtebeek 
here you go with PR
https://github.com/openrewrite/rewrite-spring/pull/510

Could you please review it and let me know your feedback.

Thanks,
Mahendra/Mahi

**Comment by timo-abele** [comment]
I think there has been a misunderstanding: `com.codahale.metrics.servlet` must be renamed to `io.dropwizard.metrics.servlet` and so on, please refer to my [original post](https://github.com/openrewrite/rewrite-spring/issues/506#issue-2169614636).

**Comment by sambsnyd** [comment]
Should be fixed by https://github.com/openrewrite/rewrite-spring/pull/510
