### ISSUE TITLE
The OutputCaptureExtension recipes does not handle OutputCapture.expect(Matcher)

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#51]
imports issues on [spring-cloud-consul ConsulAutoServiceRegistrationRetryTests](https://github.com/spring-cloud/spring-cloud-consul/blob/1da019c336fee08be42347e6f17a8664e81045e1/spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistrationRetryTests.java#L48) after it was modified by the `ExpectedExceptionToAssertThrows` and `OutputCaptureExtension` recipes.

not added
- `org.junit.jupiter.api.extension.ExtendWith`

incorrectly removed
- `org.springframework.context.ConfigurableApplicationContext`
- `org.springframework.boot.builder.SpringApplicationBuilder`

![image](https://user-images.githubusercontent.com/22326988/111536919-1541af80-8728-11eb-888e-0af454b84852.png)

**Comment by pway99** [comment]
this also affects the spring-batch JUnit 4 to 5 migration where `org.junit.jupiter.api.Timeout` is not added to the imports

[FaultTolerantStepIntegrationTests timeout](https://github.com/spring-projects/spring-batch/blob/11bac7c4e1903553a1e3b7411efc56dadd59234a/spring-batch-core/src/test/java/org/springframework/batch/core/test/step/FaultTolerantStepIntegrationTests.java#L164)

**Comment by tkvangorder** [comment]
The imports appear to be fixed now, however, there is an issue where the OutputCaptureExtension recipe was not handling the OutputCapture.expect() method which takes a Hamcrest Matcher.

**Comment by tkvangorder** [comment]
Fixed with dc0f00933fe5c3c7f12577f183e1d74fca870f88 and #54
