### ISSUE TITLE
org.springframework.util.Assert in Spring Framework 6 

### ISSUE THREAD

**Issue by pativa** [openrewrite/rewrite-spring#521]
## What problem are you trying to solve?

Migrating many projects to Spring Boot 3 / Spring Framework 6.
There does not seem to be any recipes available for Spring Framework 6.

Specifically, we encountered that `org.springframework.util.Assert` have removed some functions that were previously deprecated. See the example below for an example change.

The easiest way to migrate this would be with `org.openrewrite.java.AddLiteralMethodArgument`.

## Describe the situation before applying the recipe

```java
import org.springframework.util.Assert;

class A {
    void foo(String bar) {
        Assert.notNull(bar);
    }
}
```

## Describe the situation after applying the recipe

```java
class A {
    void foo(String bar) {
        Assert.notNull(bar, "must not be null");
    }
}
```

Ideally I guess the message would be something like "bar must not be null", but that would be a harder change to apply automatically.

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?

I have the necessary yaml changes ready and could provide that, but as there is no Spring Framework 6 migration ready, I have nowhere to put them.

So this is more more wondering if there is any interest in that I contribute these changes to the project.

**Comment by timtebeek** [comment]
Hi @pativa ! Good seeing you back here; would love to include your recipe as a first step for a `spring-framework-60.yml`; we can hook that into the rest of the migrations as usual; Feel free to throw up a rough draft PR and I'll help get it in shape and merged.

Up to now we hadn't been very specific in what changes are needed for Spring Framework 6 and Spring Boot 3, but I like your suggestion of being explicit in what folks can apply, even if the Spring Boot recipes also work for Spring Framework applications.

**Comment by pativa** [comment]
Thank you for the quick response.

I did an attempt at this change in https://github.com/openrewrite/rewrite-spring/pull/522

**Comment by timtebeek** [comment]
Indeed fixed in
- https://github.com/openrewrite/rewrite-spring/pull/522

Thanks a lot!
