### ISSUE TITLE
Spring Framework MockMvc migration recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-spring#53]
Discovered while testing `Boot2Junit4to5Migration` on spring-petclinic.  Affects [VetControllerTests](https://github.com/spring-projects/spring-petclinic/blob/c36452a2c34443ae26b4ecbba4f149906af14717/src/test/java/org/springframework/samples/petclinic/vet/VetControllerTests.java#L66-L72)

Create a new recipe for handling changes to spring framework [MockMvc](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/web/servlet/MockMvc.java)  content type

before:
```java
ResultActions actions = mockMvc.perform(get("/vets.json").accept(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk());
actions.andExpect(content().contentType("application/json;charset=UTF-8"))
        .andExpect(jsonPath("$.vetList[0].id").value(1));
```
after:
```java
ResultActions actions = mockMvc.perform(get("/vets.json")
        .accept(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk());
actions.andExpect(jsonPath("$.vetList[0].id").value(1));
```
note the above after sample does not include content-type validation.

**Comment by sambsnyd** [comment]
So the action here is to remove the contentType validation? If leaving it isn't a problem it doesn't feel like there's much urgency to do this.
