### ISSUE TITLE
In some cases, MoveAutoConfigurationToImportsFile recipe duplicates the @AutoConfiguration annotation

### ISSUE THREAD

**Issue by mankoffs** [openrewrite/rewrite-spring#548]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v2.13.2
- Maven/Gradle plugin v5.34.1
- rewrite-spring_module_ v5.13.2

## How are you running OpenRewrite?

I am using the Maven plugin, and my project

## What is the smallest, simplest way to reproduce the problem?

```java
mvn -U org.openrewrite.maven:rewrite-maven-plugin:5.34.1:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:LATEST \
  -Drewrite.activeRecipes=org.openrewrite.java.spring.boot2.MoveAutoConfigurationToImportsFile


my original file before the recipe is applied:

import org.springframework.boot.autoconfigure.AutoConfiguration;

@AutoConfiguration
public class MyConfiguration {
}


```

I also have the following files in the module:
- spring.factories, with content :
```
  org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
  com.MyConfiguration
```
- org.springframework.boot.autoconfigure.AutoConfiguration.imports, with content: 
```
com.MyConfiguration
```

To maintain backward compatibility, we need to have both: spring.factories and org.springframework.boot.autoconfigure.AutoConfiguration.imports files. With this recipe I expect that the configurations will be merged and the spring.factories will be removed. And nothing else will change.

## What did you expect to see?

```java
import org.springframework.boot.autoconfigure.AutoConfiguration;

@AutoConfiguration
public class MyConfiguration {
}

```

## What did you see instead?

```java
import org.springframework.boot.autoconfigure.AutoConfiguration;

@AutoConfiguration
@AutoConfiguration
public class MyConfiguration {
}

```

**Comment by timtebeek** [comment]
Hi @mankoffs ; thanks for the detailed report! At first glance we should have some handling for this case if I'm not mistaken.
https://github.com/openrewrite/rewrite-spring/blob/a8f526bec7f01280957cbf81adc167ad3e900e17/src/main/java/org/openrewrite/java/spring/boot2/MoveAutoConfigurationToImportsFile.java#L136-L141

This unit test in particular seems close to what you're describing above
https://github.com/openrewrite/rewrite-spring/blob/d610f71e7ad7cd15d8a153e3eea2b4ec0724cfce/src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/MoveAutoConfigurationToImportsFileTest.java#L158-L206

Would you be able to fork rewrite-spring and change the before / after blocks to match what you're seeing in an attempt to recreate this with a unit test?
