### ISSUE TITLE
Spring Framework 6.0 - ResponseStatusException method changes

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-spring#554]
## What problem are you trying to solve?

In Spring Framework 5.3, `ResponseStatusException` had methods `getRawStatusCode()` and `getStatus()`:
https://docs.spring.io/spring-framework/docs/5.3.37/javadoc-api/org/springframework/web/server/ResponseStatusException.html

In Spring Framework 6.0, these are removed. The `getStatusCode()` method from superclass `ErrorResponseException` can be used as a direct replacement for `getStatus()`, and `getStatusCode().value()` can replace `getRawStatusCode()`:
https://docs.spring.io/spring-framework/docs/6.0.0/javadoc-api/org/springframework/web/server/ResponseStatusException.html

## What precondition(s) should be checked before applying this recipe?

None

## Describe the situation before applying the recipe

```java
class A {
    void foo(ResponseStatusException e) {
        int i = e.getRawStatusCode();
        HttpStatus s = e.getStatus();
    }
}
```

## Describe the situation after applying the recipe

```java
class A {
    void foo(ResponseStatusException e) {
        int i = e.getStatusCode().value();
        HttpStatus s = e.getStatusCode();
    }
}
```

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?

Not urgent for me; probably a good first issue?

**Comment by timtebeek** [comment]
Thanks for logging the suggested improvement; I've had a quick look at the `getRawStatusCode` case using the new trait API. I'm running up against some test class path issues that stop me from adding this as is, but figured log this here as a starter for folks that want to help out.

```java
package org.openrewrite.java.spring.framework;

import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.TreeVisitor;
import org.openrewrite.java.JavaParser;
import org.openrewrite.java.JavaTemplate;
import org.openrewrite.java.trait.Traits;
import org.openrewrite.java.tree.J;
import org.openrewrite.java.tree.MethodCall;

public class MigrateResponseStatusException extends Recipe {
    @Override
    public String getDisplayName() {
        return "Migrate `ResponseStatusException#getRawStatusCode()` to `getStatusCode().value()`";
    }

    @Override
    public String getDescription() {
        return "Migrate Spring Framework 5.3's `ResponseStatusException` method `getRawStatusCode()` to Spring Framework 6's `getStatusCode().value()`.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return Traits.methodAccess("org.springframework.web.server.ResponseStatusException getRawStatusCode()")
                .asVisitor((mc, ctx) -> {
                    MethodCall tree = mc.getTree();
                    if (tree instanceof J.MethodInvocation) {
                        return JavaTemplate.builder("#{any()}.getStatusCode().value()")
                                .contextSensitive()
                                .javaParser(JavaParser.fromJavaVersion().classpathFromResources(ctx, "spring-web-6"))
                                .build().apply(mc.getCursor(), tree.getCoordinates().replace(), ((J.MethodInvocation) tree).getSelect());
                    }
                    return tree;
                });
    }
}
```

```java
package org.openrewrite.java.spring.framework;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.InMemoryExecutionContext;
import org.openrewrite.Issue;
import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.java;

class MigrateResponseStatusExceptionTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.recipe(new MigrateResponseStatusException())
          .parser(JavaParser.fromJavaVersion().classpathFromResources(new InMemoryExecutionContext(), "spring-web-5.3"));
    }

    @DocumentExample
    @Issue("https://github.com/openrewrite/rewrite-spring/issues/554")
    @Test
    void migrateResponseStatusException() {
        rewriteRun(
          //language=java
          java(
            """
              import org.springframework.web.server.ResponseStatusException;
              class A {
                  void foo(ResponseStatusException e) {
                      int i = e.getRawStatusCode();
                  }
              }
              """,
            """
              import org.springframework.web.server.ResponseStatusException;
              class A {
                  void foo(ResponseStatusException e) {
                      int i = e.getStatusCode().value();
                  }
              }
              """
          )
        );
    }
}
```

The `getStatus` to `getStatusCode` change sounds like it could be a declarative yaml recipe for a quick first migration already.

**Comment by mslowiak** [comment]
Hi @timtebeek, @nmck257 👋 
Could I pick this up?

**Comment by timtebeek** [comment]
> Hi @timtebeek, @nmck257 👋 Could I pick this up?

Great to see you've since picked this up @mslowiak ! I was away on holiday for the past week, I'll review your PR next. :)

**Comment by timtebeek** [comment]
Thanks a lot @mslowiak ! I've merged the first part of the required changes here. Next is the steps outlined in this thread 
https://github.com/openrewrite/rewrite-spring/pull/598#discussion_r1788765823 before we can close this issue. @Laurens-W can likely help out with the necessary changes there.

**Comment by mslowiak** [comment]
Thank you @timtebeek for PR review and kind words. 
I will try to implement those changes soon 👍

**Comment by Laurens-W** [comment]
> Thank you @timtebeek for PR review and kind words. I will try to implement those changes soon 👍

I think there is very little inspiration to be gained from #589 , I think a similar approach to #598 should do the job! :)

**Comment by mslowiak** [comment]
@timtebeek 
I would need a hand with that. 
I though that I am done with it, but I am struggling why the `org.springframework.http.HttpStatus` imports is not removed from the code even if I call `maybeRemoveImport("org.springframework.http.HttpStatus")` in `visitVariableDeclarations`
The draft PR is here: https://github.com/openrewrite/rewrite-spring/pull/602

**Comment by timtebeek** [comment]
Thanks a lot for picking that up @mslowiak ! In general I can say imports are only removed when the last remaining reference is removed from the types attached to various LST elements. These types can at times be in at-first surpring elements, such as method declarations, parameters, variable names, etc... The best way to explore these is with the debugger, just before a return. I've also discussed your PR with @Laurens-W just now and he's going to have a quick look, as he's worked through the same recently.

**Comment by Laurens-W** [comment]
@mslowiak I've left some pointers on your draft PR as to where `HttpStatus` still seems to be reference :)

**Comment by mslowiak** [comment]
Hi @Laurens-W, @timtebeek!
I will try to use your tips to resolve the problem. Appreciate your time to take a look there!

**Comment by timtebeek** [comment]
- Fixed in https://github.com/openrewrite/rewrite-spring/pull/602 ; thanks again!
