### ISSUE TITLE
The Junit4to5Migration recipe fails to migrate @ClassRule (of type SpringClassRule)

### ISSUE THREAD

**Issue by FieteO** [openrewrite/rewrite-spring#567]
## What version of OpenRewrite are you using?
2.16.0

## How are you running OpenRewrite?
I am applying the Maven Command Line command on a single module project.

Can you share your configuration so that we can rule out any configuration issues?
I am not explicitly changing any configuration.

Is your project public? If so, can you share a link to it?

## What is the smallest, simplest way to reproduce the problem?

```java
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.rules.SpringClassRule;
import org.springframework.test.context.junit4.rules.SpringMethodRule;

@SpringBootTest
public class SomeTest {

    @ClassRule
    public static final SpringClassRule springClassRule = new SpringClassRule();

    @Rule
    public final SpringMethodRule springMethodRule = new SpringMethodRule();

}
```

## What did you expect to see?

According to [Spring Docs - Spring Extension for JUnit Jupiter](https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/support-classes.html#testcontext-junit-jupiter-extension), `SpringClassRule` and `SpringMethodRule` are replaced by `@ExtendWith(SpringExtension.class)`.
There are two scenarios:
- `@SpringBootTest` is present on the test: `SpringClassRule` and `SpringMethodRule` should be removed. `@ExtendWith(SpringExtension.class)` is not needed since `@SpringBootTest` adds it already
- `@SpringBootTest` is not present on the test: `SpringClassRule` and `SpringMethodRule` should be removed. `@ExtendWith(SpringExtension.class)` should be added.

```java
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class SomeTest {

}
```

## What did you see instead?
No change to the class.
```java
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.rules.SpringClassRule;
import org.springframework.test.context.junit4.rules.SpringMethodRule;

@SpringBootTest
public class SomeTest {

    @ClassRule
    public static final SpringClassRule springClassRule = new SpringClassRule();

    @Rule
    public final SpringMethodRule springMethodRule = new SpringMethodRule();

}
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Generally yes, but I currently don't find the time.

**Comment by timtebeek** [comment]
Thanks for the clear description of what needs to happen here @FieteO ! Don't think I've ever seen those SpringClassRule & SpringMethodRule classes before. I've move the issue to rewrite-spring, as we have a number of other recipes this could fall under:
https://github.com/openrewrite/rewrite-spring/blob/5c7ad9800166ffb8b3619cb6cb8453d3bef18f8e/src/main/resources/META-INF/rewrite/spring-boot-24.yml#L112-L123

I think it would be a very straightforward recipe to write; starting with two unit tests on a draft PR for the cases with and without an existing `@SpringBootTest`, and then from there remove the fields as needed in a visitor. The fields can be unconditionally removed; a `doAfterVisit` could then add `@ExtendWith(SpringExtension.class)` if there is no `@SpringBootTest`.

Understandable that you might not have all the time to help with this. Do let us know if you plan to pick this up or not, such that others can step in if needed.
