### ISSUE TITLE
Upgrading the Spring-data-mongodb library in rewrite-spring latest version

### ISSUE THREAD

**Issue by ashokmarappan** [openrewrite/rewrite-spring#596]
## What problem are you trying to solve?
rewrite-spring library is still pointing to **spring-data-mongodb-2.212.RELEASE** which has the vulnerabilities identified against it. So, Sonatype is quarantined and blocked from the downloading from central repository
[Library with Vulnerability Link](https://mvnrepository.com/artifact/org.springframework.data/spring-data-mongodb/2.2.12.RELEASE)

## Describe the solution you'd like
Updating the version of **spring-data-mongodb** library to a non-vulnerable version which will benefit the teams who are using the sonatype SAST for their project so that rewrite-spring library will not be quarantined.

## Have you considered any alternatives or workarounds?
Not yet. As rewrite-spring library provides all the necessary required upgrade details for the developers

**Comment by timtebeek** [comment]
Hi! We _need_ the older version to allow you migrate to the newer alternative. While there's potentially ways around that with more effort when implementing the recipe, rest assured you're not vulnerable in any way, [as documented in our frequently asked questions](https://docs.openrewrite.org/reference/faq#why-do-artifact-scanners-detect-vulnerabilities-in-recipe-artifacts-jars).
