### ISSUE TITLE
Provide inline comment for deprecated and removed properties

### ISSUE THREAD

**Issue by ashakirin** [openrewrite/rewrite-spring#634]
Currently, OpenRewrite provides a way to generate recipes for renaming properties when a property key has changed, using:
`Run [GeneratePropertiesMigratorConfiguration.java]`.

However, when a property is removed or deprecated without an alternative, this change is not reflected in the migrated properties.

Automatically removing such properties could lead to unexpected issues because users:

- May lose important values stored in these properties.
- Might still reference these properties in custom code unrelated to Spring.

_Proposed Solution:_
I suggest adding inline comments for removed or deprecated properties (without alternatives) during the migration process. This would make the deprecation or removal clear to users, allowing them to review and decide whether to manually remove these properties as needed.

**Comment by timtebeek** [comment]
Thanks again @ashakirin !
