### ISSUE TITLE
SpringFox to SpringDoc migration doesn't work

### ISSUE THREAD

**Issue by rogeriofrsouza** [openrewrite/rewrite-spring#638]
## What version of OpenRewrite are you using?

`org.openrewrite.recipe:rewrite-spring:5.23.0`

## How are you running OpenRewrite?

I have a single module Maven project.
I ran `Migrate to 2.6` with [Intellij Idea Ultimate 2024.3 plugin](https://plugins.jetbrains.com/plugin/23814-openrewrite/versions/stable/630215) and also [the Maven Command Line](https://docs.openrewrite.org/recipes/java/springdoc/springfoxtospringdoc#usage), but both yield the same result.

## What is the smallest, simplest way to reproduce the problem?

A Spring Boot 2.6 project with springfox, using annotations and imports
```sh
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.springdoc.SpringFoxToSpringDoc -Drewrite.exportDatatables=true
```

## What did you expect to see?

The correct dependency in the pom.xml, which [according to their docs](https://springdoc.org/v1/#getting-started) may be this:
```xml
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.8.0</version>
</dependency>
```
And imports, annotations params removed, as well as annotations changed accordingly.

## What did you see instead?

The dependency cannot be found, and probably because of this error, the migration didn't work, because the imports and annotations
didn't change at all
![image](https://github.com/user-attachments/assets/acdfd519-4cd7-45b6-9e7b-d13dcd7601ac)
![image](https://github.com/user-attachments/assets/460d85bb-3d8e-4ed9-aa19-0c8fa9fd8311)

## What is the full stack trace of any errors you encountered?

No errors logged.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes, but I'll need some support most likely.

**Comment by timtebeek** [comment]
Thanks for the fix in https://github.com/openrewrite/rewrite-spring/commit/5324de6f0c20d66a13e169bab417b0f8af55d7ac @nmck257 ! Let's continue to track Docket support in that other open issue.
