### ISSUE TITLE
Migrate to Spring Boot 3.3 led to tasks.withType being added to settings.gradle instead of build.gradle

### ISSUE THREAD

**Issue by DovOps** [openrewrite/rewrite-spring#654]
## What version of OpenRewrite are you using?

Ran with the latest version of rewrite-spring deployed to the app tenant of Moderne.
5.26.0 (snapshot shown below)

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/7446c942-3b02-4233-8c71-72ee8a1c9214" />

## How are you running OpenRewrite?
Ran moderne on an open source project, and it produced the following commit:

https://github.com/finos/traderX/pull/243/commits/109320d0c4698258578c4dcc0cf19bbc89244929

This appears to have put the tasks.withType(Test) directives into `settings.gradle` when that file usually does not have access to tasks.

## What is the smallest, simplest way to reproduce the problem?

Run this recipe on the https://github.com/finos/traderX repo in the app tenant.

## What did you expect to see?

If any unit tests changes were made, `tasks.withType` would appear in build.gradle

## What did you see instead?

This change was made in `settings.gradle` which prevented me from building the project until it was removed.

Here's an example of an older run where this change was only made in one build.gradle
https://github.com/DovOps/traderX/commit/0474421e1e04c31c7df00802211435782b830141

Compare that to this change, which made the undesired changes to settings.gradle
https://github.com/DovOps/traderX/commit/109320d0c4698258578c4dcc0cf19bbc89244929

## What is the full stack trace of any errors you encountered?

n/a

## Are you interested in [contributing a fix to OpenRewrite]

Happy to contribute. Unsure if this is something wrong with my setup, or something strange happening in the recipe; At first glance I could not see a change where this was introduced, though I know this has not happened in the past.

**Comment by timtebeek** [comment]
hi @DovOps ! Indeed seems like that change should not be there; I've [ran the same recipe against the public FINOS org](https://app.moderne.io/results/WnM2rlZpO) and am seeing the same changes on traderX.
![image](https://github.com/user-attachments/assets/f89b1dac-57e4-4db4-85a9-e35c61deb957)

There's not been any recent changes to `GradleUseJunitJupiter`:
https://github.com/openrewrite/rewrite-testing-frameworks/commits/main/src/main/java/org/openrewrite/java/testing/junit5/GradleUseJunitJupiter.java

I do notice the recipe does not use any preconditions just yet, whereas it might make sense to use `IsBuildGradle` there. 🤔

**Comment by timtebeek** [comment]
Added the precondition and from my local tests that indeed fixes the issue; I'll redeploy the recipe jar to fix it on app.moderne.io as well. Thanks again for raising the issue, and all the best heading into the new year!

**Comment by DovOps** [comment]
Thanks!
