### ISSUE TITLE
Spring Boot configuration upgrade recipes

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-spring#66]
Regenerate this page in docs, merge yaml and properties versions into a single recipe. 
https://docs.openrewrite.org/reference/recipes/java/spring/boot2/config 

We should produce a new recipe whenever spring boot announces a new version.

**Comment by sambsnyd** [comment]
All reference docs generation has recently been substantially overhauled and improved, including for spring-boot recipes.
