### ISSUE TITLE
NoRequestMappingAnnotation does not add `@GetMapping`, etc. imports in every case

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-spring#79]
See `SpringMvcContractTests` in spring-cloud-openfeign until https://github.com/spring-cloud/spring-cloud-openfeign/pull/559 gets merged.

**Comment by pway99** [comment]
found a related issue where the `GetMapping` import is not added
[spring-framework MockMvcClientHttpRequestFactoryTests](https://github.com/spring-projects/spring-framework/blob/main/spring-test/src/test/java/org/springframework/test/web/client/samples/MockMvcClientHttpRequestFactoryTests.java)
![image](https://user-images.githubusercontent.com/22326988/123130610-bfa13100-d401-11eb-8db9-7635e0cae725.png)
