### ISSUE TITLE
Update SpringBootUpgrade recipes so that order does not matter.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-spring#93]
Most of the upgrade recipes that use ChangeType, ChangeMethod, etc are only relevant in a specific version of SpringBoot2. The target should be checked for @ Deprecated to ensure the change is relevant, so the recipes may be run safely on any version and do no harm.

**Comment by jkschneider** [comment]
There will always be some number of recipes dependent on a particular minor version we cannot detect. This feels like an optimization we can forgo for the time being.
